### ISSUE TITLE
About HW4 draft due on Wednesday,

### ISSUE THREAD

**Issue by ikim025** [mikeizbicki/ucr-cs100#1016]
I am just curious on how we are suppose to submit our project if it is not just a write up. What do we have to turn in as a draft if my group is a video of HW3 Signals?

We asked TA and she mentioned about turning in basic outline of what our video is about.

**Comment by mikeizbicki** [comment]
I'd want to see at least a script for all your videos.  You should also get a complete video to me as soon as possible (preferably this week).  Every student who's done videos in the past has had to completely redo the first set of videos due to mistakes I find.  The sooner you get me those first draft videos, the less you'll have to redo them.

**Comment by tristanzickovich** [comment]
For a tutorial submission, you ask us to create a folder in this repo called /tutorials/yoursubject.
Does it matter where in the repo? Would a folder under textbook/ be okay?

**Comment by mikeizbicki** [comment]
It should be under textbook.  Tutorial is a mistake.

On Mon, Feb 23, 2015 at 2:10 PM, Tristan Zickovich <notifications@github.com

**Comment by tristanzickovich** [comment]
Thanks!
