### ISSUE TITLE
^C and Vim

### ISSUE THREAD

**Issue by plusEight** [mikeizbicki/ucr-cs100#1086]
My code catches and kills the foreground process by finding the PID of the child process and eliminating it with 'kill'.
Normally, ^C seems to end all processes branching out from the parent, so I tried to SIGINT only the child process by using the 'kill' system call.
This seems to work for my own test program (code below), but when I try to run Vim in my shell and use ^Z(I use ^Z instead of ^C as I was testing this because Vim seems to intercept ^C. At the moment, my code for ^Z is identical to ^C), Vim closes and my shell just hangs with an empty terminal that doesn't respond to anything I enter in. 

```
int main(int argc, char* argv[]){
    cout << "Welcome to the test executable" << endl;
    string in;
    while(true){
        cin >> in;
        cout << "You entered: " << in << endl;
    }
}
```

**Comment by mikeizbicki** [comment]
It sounds like you're doing a lot more work than you need to. There is no need to explicitly send a signal to the child process.  As long as you enable the default signal handler (see the man page and in particular `SIG_DFL`), then you should be good.

**Comment by plusEight** [comment]
I'm not sure I understand what I am supposed to do. I read through the man page and looked up some additional resources regarding SIG_DFL. As I understand it, SIG_DFL is a 'disposition' that is passed in as a second argument to the 'signal' function call. From this source: 
http://www.gnu.org/software/libc/manual/html_node/Launching-Jobs.html
I understand that child processes ignore signal calls and we use SIG_DFL to 'set the actions for these signals back to SIG_DFL just after it is forked'.

That being said, I tried experimenting with `signal(SIGINT, SIG_DFL)` by placing it right after`int pid = fork();` and in another attempt, after `if(pid == 0)` (placing it within the child process), only to have ^C terminate my entire shell again.

I feel like I'm just throwing blind darts against a dartboard right now without a sense of direction. Maybe somebody can show me where I'm going wrong?

**Comment by churslic** [comment]
Well first, from what I can tell, `signal(SIGINT, SIG_DFL)` means that you've captured `SIGINT` but you want to make it do its default action anyways. So you're interrupting the child process, which is what you'd want anyways if the child process was in an infinite loop, yet the entire program still terminates.

So what I'm guessing is that the signal ctrl-C is still being picked up in the parent process.  So I experimented and put `signal(SIGINT, SIG_IGN)` in the parent process, where `SIG_IGN` means to simply ignore the signal, and it turns out that this works.  But the placement of `signal(SIGINT, SIG_IGN)` is important because there should be no moment during the execution of your shell where ctrl-C should terminate the program.  So putting this particular `signal` declaration at the very start of your program should work. 

Edit: If I'm totally wrong with the reasoning, someone correct me. But so far this worked for me.

**Comment by mikeizbicki** [comment]
@plusEight You shouldn't be "experimenting" with these functions in your rshell code.  You should make small example programs that just call these functions, and see how they behave.  Then, once you think you understand them, go back and try it in the bigger rshell program.

@churslic Your explanation looks good to me.  +3 pts extra credit for the good answer.
