### ISSUE TITLE
perror and opendir

### ISSUE THREAD

**Issue by Fire3galaxy** [mikeizbicki/ucr-cs100#1087]
For the getenv and opendir to search for the program, we can't seem to perror every opendir because then the rshell has many file not found error messages when it should only have one. Will it be fine to perror after all the searches just once?

**Comment by mikeizbicki** [comment]
`rshell` should not be calling `opendir` at all.  You should directly call `execv` on the path you want to execute.

It's true that you will be calling `execv` many times.  You should not be calling `perror` every time one of these fails.  Instead, this should be happening in a loop.  You only call `perror` if every iteration through the loop fails.  Since this is in a loop, you will have exactly one occurrence of `perror` and one occurrence of `execv`, so the `checksyscalls` script will say you're fine.

**Comment by Fire3galaxy** [comment]
Oh, got it
