### ISSUE TITLE
Test cases for cd, ctrl c, and execv

### ISSUE THREAD

**Issue by Fire3galaxy** [mikeizbicki/ucr-cs100#1089]
I honestly can't think of anything besides their basic uses. For example, ctrl c can be used when the prompt is waiting for input or when another program is running. I couldn't really think of anything else, except maybe having it work when multiple child processes happen at once.

Similar limits on my imagination for cd and execv.

cd: change to current directory, to a far directory, adding irrelevant additional parameters (cd only cares about the immediate next parameter), and typing a nonexistent directory.

execv: run a program in bin, run a program in the current dir (the last possible place in PATH), and run a program that does not exist.

What should I do?

**Comment by mikeizbicki** [comment]
Here's some hints for testing `cd` in addition to what you already wrote: 
1. Does your program correctly work with both absolute and relative paths?  (e.g. `cd ./usr/bin` vs `cd /usr/bin`)
2. What about when combined with io redirection/piping/connectors? (e.g. `cd < test | cat` or `pwd; cd ..; pwd`)
3. What happens when you `cd` to a file or directory where you don't have permission?

I'll let other students chime in with possible additional tests on the other aspects.

**Comment by Fire3galaxy** [comment]
why is there a ` symbol in /usr/bin?
And thank you! more cases would help.

**Comment by mikeizbicki** [comment]
It was a typo.  It's fixed now.

**Comment by Fire3galaxy** [comment]
Does your first test say that both commands should do the same thing? Bash treats the 2nd one as a reference to the root folder, not the current folder.

**Comment by mikeizbicki** [comment]
The two commands of example one do not do the same thing.
