### ISSUE TITLE
extra credit webpage completed

### ISSUE THREAD

**Issue by mchu011** [mikeizbicki/ucr-cs100#1173]
http://murphypch.me.pn

**Comment by mikeizbicki** [comment]
I like how your personality is displayed in the page :)

But this will need a bit of work before it'll qualify for the extra credit.  In particular:
1. Based on the amount of content, this should only be a single page.
2. You should never put text within images.  It should always be as normal text within the html.  Google can't read images.
3. "Codes" is not the correct word.
4. The overall layout of the page needs a bit more professionalism.  The goal of the page is that you would give this to someone who might hire you instead of a resume.
