### ISSUE TITLE
hw4

### ISSUE THREAD

**Issue by ahvino** [mikeizbicki/ucr-cs100#1202]
here are the first 3 videos again. I will be including them in the README on my gdb_tutorial repo . Please let me know what changes I need to make. I'd also like to know if there is anything else I can do to get an even higher score than what we talked about.

gdb_tutorial repo
https://github.com/antonvinod/GDB_videos

gdb_intro
https://www.youtube.com/watch?v=ufHO5rV3E24

gdb breakpoints
https://www.youtube.com/watch?v=C1hJ9XkKPBU

gdb segfaults
https://www.youtube.com/watch?v=jISPG9sK0d0

**Comment by mikeizbicki** [comment]
intro
- your voice is still too quiet
- font size and scren layout is much better
- nobody cares about the version of gdb; you need to start off with something juicy or people will just leave
- run is a good command to have in the intro, but list is not.  I can see the code in the editor on the left, so why should I care about seeing the code within gdb?  There are times when that's useful, and you should introduce list at that point.  It's not useful with your specific examples.

breakpoints
- Don't mention the gdb link at the start of each video, just get straight into the meat of the video as quick as possible
- honestly the volume is so low that I can't follow what you're saying at all, so I couldn't watch the whole video

segfaults
- The content of this video is excellent!!!  Great job!  You also have really great pacing with what you're explaining, and you're doing a great job of speaking why you type and gesturing with the mouse at appropriate locations. The volume is still a problem though.

What I would like to see is you combine the above three videos into a single video.  The starting point of the video should be the segfault video, but then add a bit more of the explanations about breakpoints and code listing (basically taking a little of the content from your previous videos).  The overall length of the result will probably be 7-8 minutes.  You should also include the cpp file you're using in your pull request so that viewers replicate your steps if they want.  If you do just this, that would be an 80/100 on the assignment.  Another ~8 minutes or so of good content could bump you up to 120/100.

**Comment by ahvino** [comment]
I am not sure if you had time to look at the repo I posted along with the links but I included the cpp file there as well (I hope that's ok). I'd also like any recommendations on the repo itself but I am still working on the videos and making the changes you suggested. I am hoping the complete repo with new videos will be ready by 4pm today. I will have the videos available on youtube as well as on my repo but I'm a little unclear as to whether I submit a link to my repo or am I just submitting the videos. Any clarification would help
