### ISSUE TITLE
HW4

### ISSUE THREAD

**Issue by Wurmie** [mikeizbicki/ucr-cs100#1231]
This is our final product with all the problems you pointed out yesterday, and more revising. 

Our Net IDs are: wlee030, cfan002, muy003, yli066.

Our final product: https://github.com/MichaelUy627/NYMPHAI

**Comment by mikeizbicki** [comment]
You guys changed a lot of the intro.  That's fine to change it, but not all of the changes were good. You've introduced lots of no-information words we can take out.

---

You have:

> Nymphai is an open source software project that connects analog sensors to the internet with the Electric Imp. 

Better is:

> Nymphai connects analog sensors to the internet with the Electric Imp. 

We already know it's open source because it's on github.  Then I replaced the verb "is" with the verb "connects".

---

You wrote:

> This project provides the means to send live data to an online data service such as plot.ly or impguru, in order to generate live-updating graphs and charts used for data analysis. 

Better is:

> This project sends live data to an online data service such as plot.ly or impguru.  These websites generate live-updating graphs.

Again, I removed the verb "is".  I also took out useless words.  What's the difference between charts and graphs?  There is none, so no need for both words.  Also, all graphs are "used for data analysis", so there's no need to include that there.  plot.ly and impguru should by links.

---

You wrote;

> This project specifically uses analog light and temperature sensors as an example template for future projects.

Better is:

> Nymphai provides example light and temperature sensors.  You can use these examples as templates for your own projects.

You always want to use the name of your project whenever possible so that people remember it.  "Specifically" is rarely a good word to use.  We already said "analog," so there's no need to repeat ourselves.  The purpose of the examples is not for the four of your to build off of (which is what your version suggests); it's for the person who's reading the writeup to build off of (which is what my version suggests).

---

Also, that first paragraph should not be in bold.  It's the first thing on the page, so I know it's important.  No need to shout it at me.

---

That introduction paragraph just repeats everything you said in your first paragraph except for the tidbit about why you called it Nymphai.  You should delete everything except that.

---

Your picture is just floating there without any context or information.  That's very confusing.

---

The "applications and extension" and "resources" sections seem like afterthoughts.  I would remove them or significantly expand them.

---

I think you will get more engagement from your readers if you move the content of the Guides files into the README.  As-is, lots of people are probably not even going to realize that those files exist.  They're pretty well hidden.  If you don't move it into the README (which is a fine choice), you need to make it much clearer that those files are there.

---

In your guides files, there's lots of mistakes.  Too many for me to go through them all.  There are spelling/grammar mistakes; stylistics mistakes (like I pointed out above for your first paragraph); and markdown formatting mistakes.  Example markdown mistakes are a lack of consistency with formatting (sometimes regular text is bold; sometimes it's normal; sometimes it's greyed out) and your numbered lists aren't done using markdown syntax.  You also still have a lot of images just floating around without any sort of caption or context.

---

If you fix the mistakes I've explicitly pointed out above, I can give you 70/100.  It's going to take a lot of reworking things to get a higher grade though.
