### ISSUE TITLE
HW4

### ISSUE THREAD

**Issue by ahvino** [mikeizbicki/ucr-cs100#1240]
Hello Mike,
I'd like to improve the score on hw4. I understand what you mean by the videos being a little rushed; however, I was under the impression that there would be 5 videos like we previously discussed. I didn't know I would need to redact them until this morning when I received your email. Currently the videos are a little over 7 minutes and I am restricted to 10 minutes on youtube. I would really like to redo and at least add another video with more detail and stronger examples in order to get the score we talked about.  I did submit the 3 original videos on Monday but I'm not sure why you weren't able to review them.

**Comment by mikeizbicki** [comment]
Yes you can resubmit and still git up to the 120 points we talked about.

I'm not dead-set on combining the first three videos into a single video.
If you think you can do it better as three separate videos, then that's
fine.  But I do think the most important thing about gdb is that it will
tell you the location of a segfault.  That's something that no other tool
can do, and it doesn't require any fancy commands like breakpoints, so that
needs to be in the first video.  That's the only reason I suggested
combining them, was to make emphasizing that easier.

As for the fork video, I suggest you sent me a revised example and script
before you go through the process of reshooting the video.  I suspect this
will take several iterations back and forth before it gets up to the
quality needed for the extra credit.
