### ISSUE TITLE
HW4 Update: BrightTime App Development

### ISSUE THREAD

**Issue by shawnjzlee** [mikeizbicki/ucr-cs100#1243]
[BrightTime](https://github.com/Team-Unguided/BrightTime)

Hi @mikeizbicki,
After visiting you at your office hours on Thursday, we have updated the readme for better readability. Please let us know how it is now. Thank you.

@shawnjzlee, @AndyThio

**Comment by mikeizbicki** [comment]
Are you guys planning on including the more detailed installation instructions?  If so you can get up 120/100 on the project.  If not I'll give you 100/100.

I might have forgotten to ask you this before, but is your download link connected to a tracker somehow so you can count how many downloads you get?  That's pretty easy to do and the feedback is very rewarding.

Do you have any questions about how to publicize it?  Post an issue here when you post it to various places so that everyone can support you.

**Comment by shawnjzlee** [comment]
Apologies for the late reply. I have updated the readme again with detailed installation instructions as well as a building & developing page that I asked about on Thursday. 

The download link is connected to a tracker. We plan on hosting it with a better provider in the near future after we get developer's upload permissions with them. 

Yes, do you think it would be better if we clean up some of the code and UI some more before we publicize it, or is this good for an initial release? Thank you!

**Comment by mikeizbicki** [comment]
Make the text `From your desktop` and `From your phone` headers using `###` or `####`; also I'd move the images below the instructions so that the actual instructions don't get lost.  

Also, I just looked at your Team-Unguided page and you don't have yourselves listed their in public.  I'd do that as well.

I've updated your grades with the extra credit.  You both did a great job! Let me know if there's anyway I can help you out in the future.
