### ISSUE TITLE
HW4 Melody Matcher

### ISSUE THREAD

**Issue by MiaoXiao** [mikeizbicki/ucr-cs100#1248]
http://miaoxiao.github.io/Melody-Matcher/

Here is our HW4 submission. Stanley and I will probably continue to update the game in the future, so we would still like feedback!

**Comment by mikeizbicki** [comment]
Do you have any type of analytics software tracking the users?  http://google.com/analytics is easy to setup and provides lots of cool information.  You can track in real time how many people are playing the game, where they come from, how old they are, and lots of other cool and creepy info.

I've attached an image of what it looks like on my laptop, which isn't super attractive.  I recommend only displaying the github banner if the resolution is large enough.  Also, for whatever reason, the game buttons don't display for me.
![2015-03-21-010018_1366x768_scrot](https://cloud.githubusercontent.com/assets/1052630/6764274/2f00b888-cf66-11e4-884e-b0f7aa0dec3c.png)

It took me a while to figure out that the letters on the keyboard were the letters I'm supposed to type to play the sound.

I think you can shorten your instructions quite a bit.  You don't need to have every last minute detail.  (You can have a more details button for that.)  You just need a 1-2 sentence description so people know what to do.  Actually, your README file is so attractive and informative that I would have the "more details" button just link there.

You're all getting 120/100.  (Can you reply to this with all your cs accounts?)  After you get the analytics setup, you're ready to start publicizing it.  Please post an issue here once you start that so that everyone can support you!

**Comment by MiaoXiao** [comment]
Thanks Mike!

rfeng001
scohe001

**Comment by mikeizbicki** [comment]
I need everyone's cs account :)
