### ISSUE TITLE
could someone spot check my assignment 5?

### ISSUE THREAD

**Issue by willccoates** [mikeizbicki/ucr-cs100#127]
if someone could proof read my assignment 5 i would be super grateful! :)
https://github.com/willccoates/ucr-cs100/tree/master/tutorials/valgrind

**Comment by katherinegallaher** [comment]
Alright here's what I'd change:

-I would change the "General" heading to "What is Valgrind?" or something like that because general doesn't really tell me what the section is about

-this sentence sounds kind of weird to me: "Valgrind has a function called Memcheck will display how many allocations you have done, how many deallocations and how many bytes were allocated and deallocated." you can change it to : Valgrind has a function called Memcheck that will display the number of allocations and deallocations in bytes

-the "finding our problem" heading could be changed to "Checking for problems" or something like that cause this section really just checks for problems you don't know you already have a problem when you run it in valgrind
- you have a coupe typos where you call valgrind "valgring"

-This sentence: "When we run this program in Valgrind using the commands:"  I feel like it should be something like: "you will run valgrind on your program with these commands" But i think your way is okay, but mine makes more sense to me

-maybe when you're explaining heap summary and everything valgrind outputs you can explain why there were still 1024 bytes in use after exiting and why theres 1 allocation and 0 deallocation. The way you have it now some people might not realize why these numbers are here

-again with the title "how to fix memory leaks" it could be changed to "how to find memory leaks" 

-maybe more of an explanation of what every line for the memory leaks output does ? cause you just talk about the third line but what do the other two mean?

-in "fix all leaks and rerun" section maybe add WHY you want to add delete
- title "More complex example" can be changed to "Using valgrind on a harder example" 
- for the second program maybe explain what it's supposed to do, people don't really want to search through an example to find out what it's meant to do just add a simple sentence after the example saying what it does

-this sentence: "If we have program like the one above, we can see that the program calls a function that allocates some memory in the main and also in a function" doesn't really make sense. I feel like it should be reworded to something like "In the example above we have two memory allocations, one in our main code and one in our doSomething function" 

-this sentence: "now if we run this program in Valgrind with Memcheck we will the get the following message:" you have two code blocks after this, one to run valgrind and valgrind output, i think this sentence should go between

-after the output for valgrind maybe explain how you're reading the output. You say that the program runs as normal printing hello world twice but you don't explain how you know that. Maybe add a sentence saying that the way valgrind works is it shows the output of the program before the heap summary

-again, explain how you're reading the valgrind output

-again, why do you need to add the deletes, what do they do? just add a sentence of why you should hav ethem 

-for this sentence "There is another function of Valgrind using Memcheck that will help you check to make sure that you allocated memory before you attempt to use it." I don't really knkow what you're trying to say. is there another tool in valgrind that you're going to use? if there is say what it is here. reword this

-for this code example, when you say your modify it slightly, say wha tyou're changing and why

-the last two -three sentences maybe put them in a 'conclusion' section?

**Comment by katherinegallaher** [comment]
I'm sorry if i seem too picky! 

these are just some of the things i would change if it was MY paper so you don't have to change everything if you think it's okay

**Comment by willccoates** [comment]
Thank you very much Katherine!! :), I will start editing tonight when I get home!

**Comment by katherinegallaher** [comment]
No prob, good luck!! if you need clarification on anything i said or want advice on anything else comment here and i'll get back to you :)
