### ISSUE TITLE
Linux installation

### ISSUE THREAD

**Issue by SparkTesla** [mikeizbicki/ucr-cs100#137]
Hi my name is Angel,
I am trying to install Linux without having the issue to accidentally erase my windows operating system. Is there a link to the Debian distribution installation? Is there a manual that gives hard drive memory specifications for Debian if installed alongside an existing OS system? Can someone help, I am trying this by myself but need more information before setting up Debian into the Hard Drive.

**Comment by mikeizbicki** [comment]
Have you looked at this page yet?  https://www.debian.org/distrib/

**Comment by SparkTesla** [comment]
Yes I did go to this page, but do i get a complete installation image for the Debian installation. Another thing, is this installation a torrent download? Because i don't want to get in trouble with the school and face expulsion.

**Comment by mikeizbicki** [comment]
Yes, this page will give you a full installation, and yes it is standard to distribute linux via torrent.  This is perfectly legal.

**Comment by SparkTesla** [comment]
Also, I found a link to a manual for installing Debian. Here is the link: http://debian-handbook.info/browse/stable/sect.installation-steps.html 
   Can this help me on the step by step process of installing Debian into my computer with an existing OS.

**Comment by SparkTesla** [comment]
There is also another question: Do I have to install Debian from a specific architecture like amd64, armel, i386, etc. or are these the wrong links for downloading.

**Comment by BridgetBennecke** [comment]
Angel, before messing around with Linux installations make sure you create a recovery drive for Windows. If you have Windows 8, it is almost impossible to get it back if you loose access to it (personal experience) unless you create a recovery drive (SD card or flash drive works).

**Comment by 2c2c** [comment]
amd64 if you have a 64 bit processor

i386 (i assume because there's no x86 link?) if you have a 32 bit processor

You'll have the choice of overwriting your current windows partition or using a separate one during setup. Never used debian but I will assume it has the ability to create new partitions at setup. you'll have to check.

**Comment by tkimva** [comment]
Yes, amd64 is for 64bit and i386 is for 32bit. For the most of distribution, the default is amd64 now since 32bit processor had released until 2004 and after 2004 almost intel and amd cpu support x86-64 instruction set. 
For the partition, general way to install is that shrinking windows partition first and install Linux into empty space. There are tons of document tutorial and youtube for howto.
Please come to office hour (WCH110, 3:40pm on Tuesday) if you have more questions.
