### ISSUE TITLE
HW0 and runtests

### ISSUE THREAD

**Issue by M-Evans** [mikeizbicki/ucr-cs100#1377]
The hw0 specs still detail the `script` submission guidelines. Will this be changed?

**Comment by mikeizbicki** [comment]
I know, sorry.  And thanks for following up with me.

The problem is that I haven't had a chance to get the documentation into a place where I think everyone would be able to understand the autotester perfectly.  We should take further discussion about this over to the gitlearn repo, though, so that it doesn't confuse the current students.
