### ISSUE TITLE
exit() vs _exit()

### ISSUE THREAD

**Issue by kevdev158** [mikeizbicki/ucr-cs100#1390]
I've read that I should be using _exit() in my child process rather than exit(). I'm not sure what the exact differences are other than that _exit() terminates the process immediately and that the child's child process are then inherited by the parent process. So why is it that _exit() is a better option?

**Comment by markasfour** [comment]
This StackOverflow Q&A gives a good explanation for why and when we should use `exit()` and `_exit()`:
http://stackoverflow.com/questions/5422831/what-is-the-difference-between-using-exit-exit-in-a-conventional-linux-fo
The first answer says that `_exit()` should be used in a child process so that in the event of an `exec` function failure, it does not interfere with the parent process (since it would be calling other files, flushing, etc.)
The second answer explains that essentially, every `main` should have one and only one `exit()`.  Thus, we should use `_exit()` in the child processes.  This has to do with how a shell uses `exec` which gets a `_start()` and `_end()` function to run your C program.

**Comment by kevdev158** [comment]
Thanks! :+1:

**Comment by mikeizbicki** [comment]
This was a great question and answer.  I'm awarding both of you +3 pts extra credit.
