### ISSUE TITLE
Grades calcgrade.sh

### ISSUE THREAD

**Issue by fvera002** [mikeizbicki/ucr-cs100#1411]
![screenshot 2015-04-17 21 04 23](https://cloud.githubusercontent.com/assets/9013439/7213931/c7532cfc-e545-11e4-86b1-200c94893dcd.png)
Is calcgrade.sh running correctly?
I have run several times and the results are the same. I know that the grades for quizzes 00 e 01 are probably wrong. What about the rest?

**Comment by mikeizbicki** [comment]
It appears your local git repo has been corrupted somehow.  Try deleting the folder `/home/csmajs/fvera002/.gitlearn`.  This should cause `calcgrade.sh` to reclone your repo from scratch.

I'm closing this issue just so that our messages don't spam everyone else.  I'll still be checking back to read your replies.

**Comment by fvera002** [comment]
I deleted the folder and ran again. 
I got this: 
![screenshot 2015-04-17 21 24 20](https://cloud.githubusercontent.com/assets/9013439/7213982/797b9e12-e548-11e4-8f68-18f6937dcfd1.png)

After running one more time, I got the same result as my first screen shoot.

**Comment by mikeizbicki** [comment]
Ok, I think I solved the problem.  Somehow your grades files got changed on
github.  So when running git pull it created a merge conflict with the
local version.

I've manually fixed everything and reentered your grades.

Sorry for the inconvenience.

**Comment by fvera002** [comment]
Thanks. 
It seems to be working fine, besides the `bad signature` thing: 

![screenshot 2015-04-17 21 55 51](https://cloud.githubusercontent.com/assets/9013439/7214062/b9c40898-e54c-11e4-9254-8ce059db97b5.png)

**Comment by mchen046** [comment]
This is what happens when I run `calcgrade.sh`. This is my first time taking the course.
![grades](https://cloud.githubusercontent.com/assets/5588203/7216600/df40fe06-e5b9-11e4-9fce-b78afd6ba614.png)

After deleting the folder `/home/csmajs/mchen046/.gitlearn` 
![grades2](https://cloud.githubusercontent.com/assets/5588203/7216623/e1f2c200-e5ba-11e4-9478-573bb87e31d7.png)

**Comment by ghost** [comment]
I too have this problem
