### ISSUE TITLE
‘strtok’ was not declared in this scope

### ISSUE THREAD

**Issue by knels012** [mikeizbicki/ucr-cs100#1421]
The error: ‘strtok’ was not declared in this scope, is given when I try to compile. I really don't get why strtok won't work. There's no special library to include, I'm using hammer and cs100, and the few results when googling suggest usual problems with this error are the compiler (I'd assume several people would have this problem if this was the reason) or a need to use strtok_r. Using strtok_r just gives me: ‘strtok_r’ was not declared in this scope, so I don't think that's it.

**Comment by ChannelJuanNews** [comment]
Hey bro! So I read your question, now check this out. If you type the command `man strtok` into your terminal you should get the manual for how the `strtok(char *restrict str, const char *restrict sep)` function works. In it, at the top where it says **SYNOPSIS** (should be third heading) and right under it, it states `#include <string.h>` which is the library needed to include in order to use that function. Hope this fixes your problem.

**Comment by opilitethesmartdev** [comment]
Hi,
I have this error too,
but _with_ `#include <string>`
I have no clue what to do

**Comment by opilitethesmartdev** [comment]
Tip: i'm in c++ (raspberry pi)
it is somethig like unstable
it works only sometimes
