### ISSUE TITLE
Grading

### ISSUE THREAD

**Issue by ghost** [mikeizbicki/ucr-cs100#1444]
Hi, when I run calcgrade.sh, none of my lab grades show up except the first lab. Also the for the grades that do show up, they have bad signatures. Is this normal?

**Comment by mikeizbicki** [comment]
The bad signatures was a result of permissions bug where I accidentally didn't give you read access to the signatures files.  This should be fixed now.

@busrac will have to help you with the lab grades.

**Comment by mchen046** [comment]
![calcgrade](https://cloud.githubusercontent.com/assets/5588203/7339388/87e7b4b0-ec21-11e4-8efb-54c8d4a06642.png)
This is what happens when I run `calcgrade.sh`. This is my first time taking the course.

**Comment by mikeizbicki** [comment]
@mchen046 If you look at the file [people/students/mchen046](https://github.com/mikeizbicki/ucr-cs100/blob/2015spring/people/students/mchen046) in this current repository, you can see there is a mistake with the `giturl` line.  This is the line the grading scripts use to fetch your grade information.  Since you have the `examplestudent`'s url, you're getting those grades instead of your own.  You should fix this by submitting a pull request with the correct url.
