### ISSUE TITLE
do_ypcall: clnt_call: RPC: Unable to send; errno = Operation not permitted

### ISSUE THREAD

**Issue by hzhu007** [mikeizbicki/ucr-cs100#1457]
When I was testing my "-l" case I found this message sometimes appeared at the beginning of my output. And sometimes the following was correct file list sometimes segfault. 
I tried to find a solution on net but only to know that is something about server.

**Comment by mikeizbicki** [comment]
This has happened for a number of students.  I'm not sure what's causing it---it's probably related to hammer's internal configuration settings---so I'll say that you will not miss any points if this error appears.

If anyone can figure out the cause of this error and (possibly) a solution, I'll give you up to +25 pts extra credit.

**Comment by ghost** [comment]
Is this issue reproducible?

**Comment by ghost** [comment]
From looking online from past cases:
1) This issue occurs when there is too many people on the server. 
2) Did you have open multiple terminals? Because of as tonight 4/28, I checked that was at least 50 or so connections a few of them from the same user. 
3) Server side configs not set properly to handle a massive connection load.

Possible solution: 
1) Run '/etc/init.d/ypbind restart'
2) Kill all your current connections and relaunch your ssh connection. 
3) Wait for the server to restart itself thus clearing its connection listing.

**However, most solutions seem to require system admin permissions to execute. In addition, this problem seems to occur when there are a lot of people on.  As mentioned on most forums, it related to either NIS or the configs for handling server loads.

**Comment by mikeizbicki** [comment]
@aso001 This is a good start on the extra credit, but you're missing two important (and related) things:

First, you're response lacks a lot of detail and is fairly generic.  When you say: 

> This issue occurs when there is too many people on the server

What I want to know is why.  What, exactly, about too many people on the server is causing this issue?  Can the kernel not handle that many processes?  Maybe it's a userspace program that can't handle the number of processes?  If so, which program?  More likely it's not actually related to processes at all but some other factor like open file descriptors.

Also, when you say:

> Server side configs not set properly to handle a massive connection load.

This isn't super useful.  What, specifically, are the settings that are misconfigured?  What should they be?  Are there disadvantages to changing it?

Of course, this is a lot of info I'm looking for, and way to much to type out in a single post.  This leads us to the second thing your post is missing: references.  You mention you found some online.  We'll that doesn't help us at all since we can't see them.

@aso001 Post your references and I'll give you +3 pts extra credit for starting on the problem.  The full amount is still available to anyone who can satisfy the requirements I listed above.

---

PS. You're right that this will require admin privileges to fix.  Once we have a very clear cause determined, I'll contact the system admins with a link to this thread and they'll be able to fix it.  Our goal is to make it super easy for them to fix it by providing all the needed information.

**Comment by fvera002** [comment]
Can we run the tests on the local lab machine instead to avoid this error in our test script? Or we should run on hammer anyway?

**Comment by mikeizbicki** [comment]
@fvera002 When we test it, we'll test it on hammer.  But it would be fine to create the script on a lab machine.

**Comment by avere001** [comment]
Seems to be fairly easy to reproduce. Just run this:

```
while true; do stat . > /dev/null; done;
```

until you see it. Should appear almost immediately and a lot.

There's seems to be discussion of the error on here:
http://www.textndata.com/forums/non-reproducible-nis-failure-193147.html

**Comment by cdixi001** [comment]
My program only screws up with -Rl or -Rla.

I don't know how you guys are getting the user and group names, but I'm doing something like this

```
struct group *grp
grp = getgrgid(s.st_gid) with an error check
and then printing grp->gr_name
```

Those lines appear only in my -l section.
Anyway, when I had those lines in the code, my program was giving me the crazy error, messing with some vector I had, and sometimes seg fault type shenanigans.
I commented them out and there's no error for me. (Can anybody confirm this?) I can't print the user and group names though :(

It's probably too late to fix it and I got things to do places to be, so I think I'll just print the uid and gid and lose a few points.

**Comment by hzhu007** [comment]
@cdixi001 I use the same way to get the names. But never seen your fault except do_ypcall error.

**Comment by hzhu007** [comment]
When I was displaying a lot of files, say nearly 200,  do_ypcall error always happened with seg fault. But my program work perfectly in any other folder with fewer files. Does anybody have any idea what was happening here?
Or if I don't display that many files, will I lose some credits? @mikeizbicki
