### ISSUE TITLE
Flags question

### ISSUE THREAD

**Issue by ghost** [mikeizbicki/ucr-cs100#1466]
Why can I not do (S_ISDIR & m.st_mode)? S_ISDIR(m.st_mode) will work but what is the difference between the two?

**Comment by avere001** [comment]
The source for `S_ISDIR` is:

```
#define S_ISDIR(m)  ((m & 0170000) == 0040000)  /* directory */
```

As you can see `S_ISDIR` requires an argument. Therefore, you can't use `S_ISDIR & m.st_mode` because you can't use `S_ISDIR` without passing it an argument.

In order to be able to use `S_ISDIR` like `S_ISDIR & m.st_mode`, you would need to change the definition of `S_ISDIR` to something like:

```
#define S_ISDIR 0170000
```

Now it makes sense to use it like that, because the preprocessor will simply replace any instance of `S_ISDIR` with `0170000`. Therefore, `S_ISDIR & m.st_mode` will be converted internally to `0170000 & m.st_mode`.
