### ISSUE TITLE
do_ypcall: clnt_call : RPC: Unable to send; errno = Operation not permitted

### ISSUE THREAD

**Issue by glaceeeee** [mikeizbicki/ucr-cs100#1470]
When running ls, occasionally the following message will show up: do_ypcall: clnt_call : RPC: Unable to send; errno = Operation not permitted. Googling the message seems to indicate that this message is related to ssh. 

I wanted to confirm whether this message was actually caused by ssh problems? If not, what could be causing this error message to show up?

**Comment by donei003** [comment]
The error message that you're speaking of has something to do with the hammer server, I'm not sure but it may be caused by the amount of people using the server. It is not a problem with your program, although it could potentially be. Professor Izbicki said that you will not lose points from that error message. However, you can receive extra credit for fixing it. Good luck!

**Comment by mikeizbicki** [comment]
See #1457
