### ISSUE TITLE
script ends when i use it for more than a minute

### ISSUE THREAD

**Issue by hkwan003** [mikeizbicki/ucr-cs100#1471]
My script ends itself when ever I take more than a minute. I can't test it comprehensively because it keeps ending itself. What can I do about this.

**Comment by mikeizbicki** [comment]
I've never seen anything like this happen before, so I can't say what's happening for sure.  Possibly you are running something else that is eating too much of your allotted resources on hammer, can that's causing script to fail.  You haven't given enough information though for me to say anything else.

If this turns out to be an error on hammer, you of course won't get docked points.  But I strongly suspect this is not an error with hammer and is an error with how you are using script.

**Comment by hkwan003** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/6343774/7439843/5c46d47c-f044-11e4-9c5c-05d3ff3bfcac.png)

**Comment by hkwan003** [comment]
so i figured out that every time I did cs100, it would close my script process.
