### ISSUE TITLE
Extra credit webpage

### ISSUE THREAD

**Issue by glaceeeee** [mikeizbicki/ucr-cs100#1479]
I remember that earlier this quarter, one of the extra credit opportunities listed in the [ec directory](https://github.com/mikeizbicki/ucr-cs100/tree/2015spring/assignments/ec). However, it's not there anymore. Was it removed as an extra credit opportunity?

**Comment by htang014** [comment]
I would like to know as well

**Comment by mikeizbicki** [comment]
I removed this because students were making low-quality webpages expecting to get lots of extra credit.  If you have or create a high quality webpage, then I will still give you extra credit.  But I wouldn't make one just for extra credit.  It'll probably take about 50 hours of work to make a webpage good enough to get extra credit.

**Comment by ghost** [comment]
So its up for grabs, it just the quality that we put into it.

**Comment by mikeizbicki** [comment]
Let me be a bit more detailed on the criteria:  If an engineer from Facebook/Google/Microsoft would look at the webpage and say "we should hire this person" then you will get extra credit.  If it doesn't make that kind of reaction then you will not.  This will be worth 10pts extra credit max.

**Comment by ghost** [comment]
ok noted ...

**Comment by htang014** [comment]
Darn. Why the demotion to 10 pts?

**Comment by mikeizbicki** [comment]
@htang014 Because I want to discourage you from doing this.  For some reason last quarter students thought this would be an easy way to get extra credit.  But many students were disappointed that after spending 10 hours on a webpage I didn't think it was good enough and awarded no extra credit.  I'm trying to emphasize that this is the _hardest_ way to get extra credit.  The only reason I'm offering any extra credit is to reward students who are doing this anyways.  If you're doing this for the extra credit, then it won't be worth it.
