### ISSUE TITLE
hw4 idea

### ISSUE THREAD

**Issue by zzhou007** [mikeizbicki/ucr-cs100#1492]
@kchan049 and I
Idea 1 
documentation on remaining sys calls and make videos for system calls that are not in ucr-cs100/textbook/assignment-help/syscalls/ such as link, unlink, rmdir
Idea 2
documentation on file type hardlinks and softlinks and memory blocks with videos
Idea 3
A guide on how to do a minimal debian testing install to set up wifi, sound, and system tools such as gcc gdb and setting xmonad along with setting up .xmonad/xmonad.hs

**Comment by mikeizbicki** [comment]
I think a combination of ideas 1 and 2 would work well.  In particular, if you improve the lab so that it includes a nice tutorial on all those topics, I could see you earning some nice extra credit on the assignment.  I'm a little bit hesitant to approve a video project though.  They are very hard to do well, and students usually grossly underestimate the time it takes to complete them, so they often don't come out well.

Before I approve this project, I'll want to see:
1. Give a paragraph description of how you would modify the lab so that your tutorial doesn't just completely give away the answers.  (You might want to talk to me in person about this to bounce around some ideas.)
2. Tell me a bit more about the style of video you would do.  For example, which existing video would it be most similar to?

**Comment by zzhou007** [comment]
Combining idea 1 and 2, there would be a video about the uses of link and unlink as a screen capture with sound that shows linking and unlinking along with what it does to the file such as writting to one linked file and such. There would also be screenshots of what is going on and a short description of it as a written portion. There would also be a written portion that shows what is actully going on as well as comparing hard, soft and symbolic links and discussing when is you should use use with one. 
This does not give away the answers to the lab because it only shows what linking and unlinking does. It does not actully tell people what to do with the -r flag that requires recursion.

**Comment by zzhou007** [comment]
I posted this quite a while ago how is the idea?

**Comment by mikeizbicki** [comment]
Sorry I missed this the first time.  It sounds good.  I'll want to see a rough draft of the video by the next deadline as well as an outline of the specific examples you'll be writing about.

**Comment by zzhou007** [comment]
we have 2 rough draft of videos 
https://www.youtube.com/watch?v=LPIMLR4simU
https://www.youtube.com/watch?v=j_BgOf2Ti-s
