### ISSUE TITLE
HW4 Ideas

### ISSUE THREAD

**Issue by ColdNightHour** [mikeizbicki/ucr-cs100#1493]
My two partners and I have a few ideas that we would like to do. Tell us if they could be possible to do as a final project:
Idea 1: Making a basic website that houses github commands that we use as well as other commands, in order to dumb in down for beginners. A lot of sources when I started were very hard to understand and we believe that if we make a simple website for beginners of git to go to it would benefit a lot.
Idea 2: Making documentation on open source licenses. For those who are in open source and don't know about the license types, we can make documentation that'll explain them in laymen terms. 
Please let us know if any of these are good, if not we'll think of some more before tomorrow night.

**Comment by mikeizbicki** [comment]
Idea 1:  There are already a LOT of these websites, many of which the developers have put thousands of hours into.  It's hard for me to imagine you improving the situation here.  But if you have a concrete idea of how to do this run it by me.

Idea 2: I like this idea a lot more.  I think a description of _just_ licenses is probably the amount of work for 1 student, but if you expand your writeup to be something like the "history of open source software" then I think it would be good for 3 people.  We should talk about this in person a bit though so that we're on the same page.

Also, please reply with the github or cs accounts of your partners.

**Comment by ColdNightHour** [comment]
Thanks! My partners are jruel006 @CompKev824 @hkwan003 Calvin posted another idea we had.
