### ISSUE TITLE
Test Case Table Program (Hw #4)

### ISSUE THREAD

**Issue by aesgu001** [mikeizbicki/ucr-cs100#1496]
My proposal for this project is dedicated to helping both instructors and students make their test cases more readable. The Test Case Table Program shall allow them to list test cases, and place them neatly either in standard output or in a file they wish to store the results. The table's format is similar to the template shown in the following link:

https://github.com/mikeizbicki/ucr-cs100/tree/2015spring/textbook/bestpractices/WritingGoodTestCases

This program shall use commands that will guide it in generating the table along with its own manual page that will help beginners in using them. Hopefully, in the future, it would contribute to enhancing not only your grading style, but that of other Computer Science instructors as well. I believe that, in turn, incoming students will be more eager in honing their programming skills!

If anyone wishes to help me turn this vision into reality let me know via email!
aesgu001@ucr.edu

Currently on board:
nchun003

**Comment by mikeizbicki** [comment]
Some previous students have already made some good progress in this direction.  It's not quite ready yet, so another student will be working to improve it.  (See #1484.)  I'd be happy to have the two of you join them, though.  That should be enough manpower to get everything really well polished so that we can use it in the next class without any hiccups.  Does that sound okay?

**Comment by aesgu001** [comment]
Sounds fine to me. I'll email him about this right away.

**Comment by alvtdev** [comment]
I have just spoken to Michael about this, and unfortunately, this feature has already been implemented.
