### ISSUE TITLE
HW4 Proposal :]

### ISSUE THREAD

**Issue by jle034** [mikeizbicki/ucr-cs100#1501]
Hi Mike,

I noticed that there is currently no tutorial that focuses on grep. I think it's a very common and useful command. I would like to write a tutorial going into more detail about its uses (flags, etc.) for my hw4.

**Comment by mikeizbicki** [comment]
Sounds great!  I'd like to see this integrated somehow with the regular expressions tutorial and the sed tutorial, since they're all very similar.  I don't think this integration should take too much extra work, but I'm willing to give you up to 25 pts extra credit on the assignment if you can pull it off.  Sound good?

**Comment by jle034** [comment]
That sounds awesome! Thank you so much. I will look into it :]
