### ISSUE TITLE
HW4

### ISSUE THREAD

**Issue by tortas** [mikeizbicki/ucr-cs100#1510]
For my final project, I would like to do a writeup on some of the new and improved features implemented in C++11 and C++14. This includes but is certainly not limited to:
- Type inference
- for-based range loops
- Lambda functions
- Default and delete constructors
- Initializer lists
- Hash tables

Of course, plenty of examples of uses and syntax would be included. The writeup will be focused on more of the functionality improvements of the language.

**Comment by mikeizbicki** [comment]
That's a fine topic.  But there are already two writeups on this:
1. https://github.com/mikeizbicki/ucr-cs100/tree/2015spring/textbook/C%2B%2B/C%2B%2B14Standards
2. https://github.com/mikeizbicki/ucr-cs100/tree/2015spring/textbook/C%2B%2B/C%2B%2B11features

So what I would want from you is to combine these two writeups with your own into one nicelt integrated summary of c++11 and 14.  Since combining all these writeups together nicely will take some work, I won't expect you add descriptions of as many new features as you would have to otherwise.  Sound okay?

**Comment by tortas** [comment]
Yeah, sounds good. Thank you.
