### ISSUE TITLE
HW 4 topic

### ISSUE THREAD

**Issue by jkinc002** [mikeizbicki/ucr-cs100#1511]
So we talked about me doing a sort of restructure/edit of some already existing syscall tutorials. I took a look in the /textbook/assignment-help/syscalls directory of the repository and am wondering which ones specifically you were saying could be re-done. 

Also I think I'd like to include a quick documentation on the  syscall "localtime" that I used to convert the 'st_mtime' value from the 'stat' struct into month/day/time output used for the '-l' flag from hw1.

**Comment by mikeizbicki** [comment]
I like the format of: `dir.md` and `fd.md` because they have more of a tutorial feel than a reference feel.

I want to change the format of `exec.md`, `getinfo.md`, `io.md` and `stat.md` so that they follow the tutorial format of `dir.md` and `fd.md`.

There's actually already a time writeup at: https://github.com/mikeizbicki/ucr-cs100/blob/2015spring/textbook/C%2B%2B/time/time_tutorial.md.  This is also more of a reference than a tutorial, so I'd like this reworked as well.  

For your project, I'd expect you to pick 3 of these files and redo them.  If you do an exceptional job on 2 of them, that would also work.

**Comment by jkinc002** [comment]
I'll rework getinfo.md, stat.md, and the time one then.

**Comment by jmeji011** [comment]
In that case, I would like to rework io.md and exec.md to make it follow the step by step format of dir.md and fd.md

**Comment by mikeizbicki** [comment]
Sounds good!

**Comment by jmeji011** [comment]
I did not know how to show my progress on hw4 so I am just going to paste the markdown file code here. This is some of the code for the rework of io.md and it shows an example of how to use dup(). I don't know if this is somewhat of what you were looking for, I tried to make it similar to the other files you mentioned, but also keeping some of the reference stuff. I will be doing the same for the other syscalls, but just wanted to know if I am on the right track. I can finish the rest and show you soon after I get some feed back (:

**_Input and Output System Calls**_

This markdown file demonstrates how to use the system calls `dup` and `pipe`.
These system calls involve manipulating file descriptors.

The three standard file descriptors are shown in the table below.

| **Integer Value** | **Name** | *\* <unistd.h> Symbolic Constant** | <stdio.h> File Stream |
| --- | --- | --- | --- |
| 0 | Standard Input | STDIN_FILENO | stdin |
| 1 | Standard  Output | STDOUT_FILENO | stdout |
| 2 | Standard  Error | STDERR_FILENO | stderr |

**dup(System Call):**

**Required Include Files:** `#include <unistd.h>`

**Function Declaration:** `int dup(int oldfd)` Where `oldfd` is the file descriptor you want to create an alias for.

**Return Value:**  `dup()` returns the value of the new file descriptor, which is always the smallest available
file descriptor. Since we have 0,1,and 2 used for the standard file descriptors show in the table above, `dup` will return 3. When an error occurs, `dup()` will return -1.

The following is an example of how `dup()` is used to redirect to standard output and using the fact we know it uses the smallest available file descriptor. The source code can be found at [`io_code.cpp`](./io_code.cpp).

We begin by by opening a file that will be used for writing only.

```
int outfd = -1

    outfd = open("filename.txt", O_WRONLY | O_CREAT | O_TRUNC, S_IRWXU | S_IRGRP | S_IROTH);

    if(outfd < 0)
    {
        perror("open(2) file: " filename.txt);
        exit(1);
    }
```

Notice that output file descriptors (`outfd`) less than 0 are invalid and proper error checking is displayed.

We will now close Standard Output and the lowest available file descriptor will now become `STDOUT_FILENO`, which we now know is the integer value 1. Once again, proper error checking is needed.

```
    if(close(STDOUT_FILENO) < 0)
    {
        perror("close(2) file: STDOUT_FILENO");
        close(outfd);
        exit(1);
    }
```

We can now copy `outfd` onto `STDOUT_FILENO`.

```
    if(dup(outfd) != STDOUT_FILENO)
    {
        perror("dup(2)");
        close(outfd)
        exit(1)
    }
```

The final step after everything has been successful is to close the original file:

```
    close(outfd);
```

Remember: Closing files is very important!
Standard Out should now be a file.
