### ISSUE TITLE
HW 4 Proposal

### ISSUE THREAD

**Issue by skama004** [mikeizbicki/ucr-cs100#1515]
My partners (Ant' Hannes Phillips and Divyansh Choudhary) and I were thinking of creating a game with a series of mini games helping students with git and vim commands so they can gain a better understanding in a more interactive and hands on manner.

**Comment by mikeizbicki** [comment]
You'll need to be MUCH more specific about what the game would do before I can approve the project.  I think a sequel to the the git-game (https://github.com/hgarc014/git-game) would be hugely popular.  If you decide to do this, then you'll need to give me a rough idea of what other git features you'd be testing.

**Comment by skama004** [comment]
We wanted to base the game off the example you used in class a few weeks ago with pushing and committing from your computer to the cloud, but make it more of a RPG style game in which your goals are to connect and push on the cloud. And that would be a rough idea of what we would want the git game to be like. The vim game would focus more on getting used to the style of vim and would operate with different vim commands. The game would have a character with a health bar and with improper commands the health will go down.

**Comment by mikeizbicki** [comment]
We'll have to talk about it in person for me to get a better feel for what you're imagining.  In particular, I'll want to see some hand sketched screenshots and levels.  Can you do this by Friday?

**Comment by skama004** [comment]
Yes! We will outline everything and show you as soon as possible before Friday.

**Comment by skama004** [comment]
So we have strayed away from this topic and have decided to make a bit of a more interactive program to help with vimrc settings. We will make a repository and have students be able to clone our repository and with our program they can customize their own vimrc settings as such. It will feature big components of vimrc such as tabbing, line numbers, and other features, but we have begun planning out this.

**Comment by mikeizbicki** [comment]
I don't think this will work for two reasons.  First, I don't understand how you could make an interactive vimrc tutorial.  Second, there are already students working on vimrc, so you would be duplicating their effort.

**Comment by divyanshch** [comment]
We will be doing documentations for the following system calls:
sigaction, chmod,  setenv, getenv, link, and unlink
All these would go into the the specific folders they belong to in the assignment help syscalls page.
setenv and getenv would go into the getinfo.md file.
However, we are confused on where to put unlink, link, chmod, and sigaction.
Should link and unlink go under the dir.md file?
And should we make a new file for these chmod and sigaction or is there a certain place we should put them?

**Comment by mikeizbicki** [comment]
Your proposal is a little light for three people since the `chmod`, `setenv`, and `getenv` are so simple.  If you do just those functions, the maximum you could get is an 80.  If you additionally cover the `chown` and `symlink` syscalls, then the max you can get is 100.  But remember:
1. Quality is more important than quantity.  Your grade will be better if you do a good job on the smaller set of syscalls than a poor job on the larger set.
2. You are not just repeating the information on the man page.  That will get you no credit.  You must come up with interesting examples for each of these functions, and explain the function by explaining the example.

Also, I don't want you to modify the existing writeups.  This would conflict with other people's projects.  Your writeups should stand alone by themselves.
