### ISSUE TITLE
Extension?

### ISSUE THREAD

**Issue by htang014** [mikeizbicki/ucr-cs100#1546]
I think I speak for a lot of people when I say I could really, really use an extension.

**Comment by skama004** [comment]
I'd like to follow up on the extension request. A lot of students are having trouble getting this to be working and a few more days would really be beneficial. So is there any chance we can have one?

**Comment by ColdNightHour** [comment]
I third this request. Despite asking Busra for help, I cannot seem to get some things working.

**Comment by hkwan003** [comment]
Its not that we don't have questions to ask to bring to office hours. Its just our errors take time to debug. I have gotten multiple out of range errors and I have spent a couple hours already trying to debug that. I am not going to come in and ask about how to fix the out of range error because it is such a elementary bug that I should be able to do it. I understand how to use the syscalls and commands conceptually, It's just inplementing them takes trial and error. Therefore, I would prefer to have more time to work on this assignment rather than turning in a error filled program.

**Comment by donei003** [comment]
I second this notion. I have class during your office hours and therefore I cannot come to them to ask questions. Asking questions after class is not feasible since there is usually a group of 5+ students there having problems of their own. Busra helped me quite a bit but that was only because I was able to fully explain my situation and get a detailed answer/direction. I'll be asking some questions tomorrow during class but I would much appreciate an extension on this assignment. These concepts by themselves are not easy to grasp and linking both piping and io redirection in one command is challenging.

**Comment by mikeizbicki** [comment]
Possibly.  We will talk in class tomorrow.
