### ISSUE TITLE
Piping Output "Problem"

### ISSUE THREAD

**Issue by donei003** [mikeizbicki/ucr-cs100#1548]
Hello, I am working on chaining piping together but I have a "problem" of sorts. At the beginning of my loop I print out a '$' like bash. At the end of my nested loop where piping takes place, I am calling execvp. However, for some reason unbenounced to me, the '$' is printed before the output of execvp. 

For instance, the command "ls | cat | cat" would have the following sequence of output:
$ ls | cat | cat
$ f1
f2
f3
f4

This program will then wait at the line below f4 where it is waiting for user input because of getline. Any suggestions?

**Comment by avere001** [comment]
Make sure you wait for all children to close before asking for more user input. My guess is that you are only waiting once per chain when you need to wait once per child.

**Comment by donei003** [comment]
I've tried that, but when I do that cat doesn't actually close. It will print out the appropriate output, however, it still takes input like normal cat would do. But, it doesn't output it.

**Comment by donei003** [comment]
Fixed! The problem was, was that I was waiting on every child process except on the first one created. Fixed by only waiting on the last process.

Thanks for the help.

**Comment by mikeizbicki** [comment]
@donei003 Waiting on only the last child is incorrect.  Here are two bugs that this would cause:
1. What if the last program terminates 5 hours earlier than the first program?  Then your shell will prompt the user for more input, but the first program could still be outputting stuff to the screen.  This would create the same output you had above where the prompt is being displayed in the middle of the program's output.
2. Since you never wait on some children processes, they become zombies.  That means they are still processes and using up resources.  On hammer, you are only allowed to have 23 processes running at once.  so if you have 22 zombies (children you didn't wait on) plus your rshell open, you can't create another process, so `fork` will fail.

**Comment by donei003** [comment]
As a matter of fact, the second problem you described is occurring in my program. I was going to ask you today how to kill those processes. So, can I kill those processes and if not then how are we not going to wait. In class you said they have to be running concurrently. Well, if you wait for the child processes to terminate, then obviously they are not concurrent.

**Comment by mikeizbicki** [comment]
You shouldn't wait on each the process immediately after you launch it.  You should launch all the processes at once, then you wait on them all at once.

**Comment by donei003** [comment]
The way that I am doing my piping as well as my entire rshell is one command at a time. As in, when the command "ls | cat" is input, when we start the pipe, my program has no idea that cat even exists. To be more clear, I begin my loop and find "ls", then once I find the '|' I open up the pipe and call execvp in the child process. I then come back to the top of the loop and that is where I find "cat". Once I have found cat, I finish off the pipe and call execvp a second time. In order to do it in my case, should I be storing the process IDs then after the last pipe have a loop to wait for the processes?

**Comment by mikeizbicki** [comment]
@donei003 It is possible to correctly wait on the processes the way you propose.  There are also other solutions that would be correct.
