### ISSUE TITLE
Wait for multiple forks

### ISSUE THREAD

**Issue by TheBoop** [mikeizbicki/ucr-cs100#1553]
You mentioned in class that it is incorrect to have the wait in each individual parents. Looking at the graph you drew in class we are suppose to have as many waits in the last parent as number of children. Thus how do we know which parent is the last parent to put all the waits in?

**Comment by mikeizbicki** [comment]
I'm not sure I understand what you mean by "which parent is the last parent".  If you call `fork` five times, then after the fifth, you're in the last parent.

**Comment by TheBoop** [comment]
Something like
pid_t pids[#ofpipes];
for( i upto #of pipes){
    if ((pids[i] = fork()) < 0) {
        perror("fork");
        abort();
    } else if (pids[i] == 0) {
        runargs();
        exit(0);
    }
}
for( i upto #of pipes) {
      pid = wait(&status);
}

Also how do we know which child runs what parts of arguments?
ls -l -a | grep . | tee outfile
fork1 runs ls
fork2 runs grep
fork3 runs tee
all at the same time

**Comment by srufe001** [comment]
That code looks good. As for how to tell which child was which command, you can use wait's return value. It's the pid of the child that returned.

**Comment by TheBoop** [comment]
If I do
for( i upto #of pipes) {
      pid = wait(&status);
      printf("Child with PID %ld exited with status 0x%x.\n", (long)pid,
status);
}
The code above has an output
work
work
work
Child with PID 7693 exited with status 0x0.
Child with PID 7694 exited with status 0x0.
work
work
Child with PID 7692 exited with status 0x0.
Child with PID 7700 exited with status 0x0.
Child with PID 7695 exited with status 0x0.
work
Child with PID 7696 exited with status 0x0.
work
Child with PID 7697 exited with status 0x0.
work
work
Child with PID 7698 exited with status 0x0.
Child with PID 7699 exited with status 0x0.
The does that mean the processes are running simultaneously?
What if work requires in output from another work that has not been ran yet?
Doesn't that throw an error?

**Comment by srufe001** [comment]
What is causing "work" to print?
As far as running the processes simultaneously, I believe they are running simultaneously, because you did all of your forking before you did any waiting.
I'm guessing "work" is what gets printed when you do `execvp`. If so, I don't think it's a problem that some children are finishing before other children have started. There's nothing you can or should do about that, as far as I know. The children that finished early didn't overflow the pipe, so they finished normally. The important thing is that you do not `wait` for the first child to finish before you run the second.

**Comment by TheBoop** [comment]
Ok thank you, I believe I have a better understanding now.
