### ISSUE TITLE
creating a vector of int arrays

### ISSUE THREAD

**Issue by mchen046** [mikeizbicki/ucr-cs100#1557]
Can anyone give some insight on how to create a vector of int arrays, something like
 `vector<int[2]> pipes` 
For some reason, the compiler does not allow the user to store multiple int arrays into a container.

Update: I found something that may be of use to some of you.
http://www.cplusplus.com/forum/beginner/90974/

**Comment by avere001** [comment]
I know this is closed, but here is another solution:
https://stackoverflow.com/questions/12184828/compiler-error-with-c-stdvector-of-array

basically, instead of using `vector<int[2]>` pipes you can use `vector<array<int,2>>`
since pipe requires an `int[2]`, you can convert from `std::array<int,2>` to `int[2]` with `myarray.data()`
