### ISSUE TITLE
HW 4 draft zzhou007 and kchan049

### ISSUE THREAD

**Issue by zzhou007** [mikeizbicki/ucr-cs100#1600]
You said in class that we had to make a seperate issue for the hw4 draft. 
kchan049 and I made the scripts for the videos and will add on the documentation in the following repo.
https://github.com/zzhou007/hw4
So far, we made two videos on links, data blocks and inodes. We will have some more videos on some of remaining sys calls.
https://www.youtube.com/watch?v=LPIMLR4simU
https://www.youtube.com/watch?v=j_BgOf2Ti-s
This was our original post
https://github.com/mikeizbicki/ucr-cs100/issues/1492

**Comment by mikeizbicki** [comment]
You do not have to create a repo for this assignment.  Your final submission will be as a pull request into this repo.

hard/soft links video:
- What's with the static at the beginning?
- Speak up, I can barely hear you.
- Why doesn't your presentation start full screen?  I don't want to see all that crap on your desktop.
- You have no introduction you just start with "visible to user".  I have no idea what you're talking about.
- You voice is very stilted and sounds confused.
- I stopped watching after about 30 seconds because I couldn't understand anything that was going on.

inodes/datablocks
- The viewer doesn't care who your partner is, and we already know it's a presentation.  No need to tell us this stuff.
- Why is there all that wasted space on your desktop?  Your font is tiny, and I can't read it.  Make it bigger.
- The stat manpage lists 7 types of files
- You should be running `ls -l` if you're trying to convince me those files have different types
- okay, I just saw that you do run `ls -l`... so why'd you waste time running `ls` first?
- I don't want to see you switching between power point and terminal.  Use editing software.
- I can't follow any of your explanation, so I stopped watching after about a minute.

For both videos, you need your presentations to be done under Linux, not Mac.

Both of your videos seem very rushed.  You have a LOT of work to do on them.
