### ISSUE TITLE
Markdown Ordered List Syntax Question

### ISSUE THREAD

**Issue by markasfour** [mikeizbicki/ucr-cs100#1616]
I was looking at the [raw file for the hw3 README.md](https://raw.githubusercontent.com/mikeizbicki/ucr-cs100/2015spring/assignments/hw/hw3-signals/README.md) and I came across something peculiar with the ordered list syntax.

Here is the instance:

```
1. Implement the `cd` command.
Every time this command is run, you must update the `PWD` and `OLDPWD` environment variables appropriately.
This will require using the `chdir`,`getenv`, and `setenv` functions.
Your implementation must support the following forms:

    a. `cd <PATH>` will change the current working directory to `<PATH>`

    b. `cd` will change the current working directory to the user's home directory

    c. `cd -` will change the current working directory to the previous working directory

1. Change your prompt so that it displays the current working directory.

1. The shell should not exit when the user types `^C`.
Instead, the current foreground job should receive the `SIGINT` signal.
If `SIGINT` kills the job, then control should return to your shell.
```

I noticed that in the raw file, the three hw3 requirements are listed as `1.`, `1.`, and `1.` whereas it somehow correctly appears as `1.`, `2.`, and `3.` on github.  

Documentation I have found on ordered lists in .md files do not mention numbering to be automatically configured. 

I am wondering why this works.  
Is this a special case with github or does it have to do with how HTML creates an `<ol>` with numbered `<li>` elements?

Thank you,
Mark Asfour

**Comment by mikeizbicki** [comment]
Great question!  +3 pts extra credit.

This has nothing to do with html's `<ol>` and `<li>` elements.  Markdown and html are completely separate and have nothing to do with each other.

The answer is that github uses a program called Pandoc to convert markdown files to html.  (Pandoc supports dozens of other output types as well, like word documents and pdfs.  That's why I say markdown and html have nothing in common.)  

Pandoc obeys the unix principle of "be strict in what you output, but be lax in what you accept".  That means pandoc will output html that can be rendered in any web browser.  But the input doesn't have to be perfectly formatted---the syntax of `number-` is always used to indicate the next element in the ordered list.  Many developers actually prefer to always number their lists in markdown using `1.` everywhere.  This makes it easier to reorder the lists without having to manually adjust the numbers.
