### ISSUE TITLE
Blitz Tutoring at the ARC

### ISSUE THREAD

**Issue by cbarb005** [mikeizbicki/ucr-cs100#1673]
For those of you who need some help on your write-ups, the ARC offers walk-in tutoring, or "blitz tutoring" as an alternative to formal tutoring appointments.

During these sessions mall groups of students are taken from the lobby to go see the tutors; given the volume of students, it is essential to come prepared. Students are expected to have proofread hard-copies for the tutors to look at, and should come prepared with specific issues to discuss. Because the tutors likely have little background in CS, this is a good opportunity to make sure your writing is clear and accessible!

If interested, the next session is tomorrow from 10AM to 1PM at the Academic Resource Center.

**Comment by cbarb005** [comment]
There will also be a couple of writing tutors at Orbach on Sunday, from 5 to 9 PM, for anyone who still wants feedback!

**Comment by mikeizbicki** [comment]
If you attend these sessions, then in order to get the extra credit you will need to do two things.  First, I will need to see some proof that you attended.  The staff will be happy to write you a note.  Second, you will need to write a note in your final pull request to remind me.  The extra credit will be added to the hw4 grade.

@cbarb005 I've already seen your proof, you just need to remind me when you submit.
