### ISSUE TITLE
hw4 terminal-game evaluation submission

### ISSUE THREAD

**Issue by fundamelon** [mikeizbicki/ucr-cs100#1786]
Hello,

https://github.com/fundamelon/terminal-game-tutorial is now updated with all the latest additions and changes.  Some of the later tutorials are still nearing completion, but the first couple have been polished and tested thoroughly, and will serve as examples.  We would appreciate any feedback you can give us on how to improve this project.  And we look forward to doing that Extras section!

**Comment by mikeizbicki** [comment]
The technical content of your writeup has a few minor mistakes, but overall seems fine.  The writing and organization, however, is very much lacking still.  I remember talking to you all about focusing on quality instead of quantity, but it seems like you're doing the opposite.  I can't leave more detailed line-by-line feedback since this isn't a pull request.  If you want more detailed feedback or to talk about grades, please come to my office hours tomorrow.  Otherwise, I will grade whatever you have up at noon tomorrow.

**Comment by fundamelon** [comment]
We can't make it to office hours since most of us moved out of Riverside already.  Is it still possible to get more detailed feedback from you before the final submission?

Edit: [Pull request is up](https://github.com/mikeizbicki/ucr-cs100/pull/1809)
