### ISSUE TITLE
Testing &

### ISSUE THREAD

**Issue by katherinegallaher** [mikeizbicki/ucr-cs100#24]
I'm trying to do what Mike said in lecture today to test &, trying "cat /dev/random > rand &"
and > doesn't seem to work? It does not create a file called rand but it kind of does run in the background, the random numbers still show in the terminal but it allows me to write in commands. 
Is there a reason that output redirection does not work ?

**Comment by mikeizbicki** [comment]
hmmm... my example wasn't as good as I thought it was.  Output redirection is a feature of the bash shell, and something you'll be implementing in a future homework assignment.  That's why it's not working.

Based on the description of your output, it sounds like `cat` is being correctly sent to the background.  You can kill the process using the `kill` command to stop the random characters being printed.
