### ISSUE TITLE
using c++11

### ISSUE THREAD

**Issue by 2c2c** [mikeizbicki/ucr-cs100#253]
I want to make sure it's okay/not okay to use in assignments.

**Comment by mikeizbicki** [comment]
According to the instructions, we will be grading your assignment by running the following commands:

```
$ git clone  http://github.com/yourusername/rshell.git
$ cd rshell
$ git checkout hw0
$ make
$ bin/rshell
```

on `hammer.cs.ucr.edu`.  As long as those commands work on that machine, I don't care what you do.  So you are free to use whatever C++ extensions are available there.

In order to enable C++11 features, you must run the command `cs100` once you log into hammer.  This command changes your environment in a couple of other ways too, but it will be in this environment that I expect your code to be able to run.
