### ISSUE TITLE
Confusing behavior for exec.cpp

### ISSUE THREAD

**Issue by jesuscreyes** [mikeizbicki/ucr-cs100#256]
Hi. I'm trying to mess with the given exec.cpp to figure out how to implement it in my assignment, but there's a confusing error that I'm encountering.

When I compile and run it, it works fine.
![screenshot from 2014-10-18 13 39 01](https://cloud.githubusercontent.com/assets/9061700/4691122/2b2f5d86-5707-11e4-871d-f6c961bce6e2.png)

But, say I try to declare a string, like so, I get this weird error.
![screenshot from 2014-10-18 13 43 21](https://cloud.githubusercontent.com/assets/9061700/4691130/87ece3b8-5707-11e4-80bb-02c7f6de7e76.png)

Any explanation of why this is happening will be greatly appreciated.

**Comment by jhollister** [comment]
The argv array has to be null terminated for execvp to work properly. Both of these programs should have issues but you may not have seen anything on the first one because there happened to be a 0 outside the bounds of argv.

So you would change "char *argv[3]" to "char *argv[4]"
and then add argv[3] = 0

**Comment by mikeizbicki** [comment]
jhollister's answer is correct.

**Comment by jesuscreyes** [comment]
Thanks so much!
