### ISSUE TITLE
Multiple commands

### ISSUE THREAD

**Issue by DustinPham** [mikeizbicki/ucr-cs100#264]
How do we go about implementing the multiple commands? Such as:
"ls -a; ls"

When I run my program and try doing that, execvp runs all of them at once causing an error. I'm guessing it sees "ls -a; ls" as "ls -a ls" (after parsing) which is not a viable command in bash.

**Comment by tkimva** [comment]
As written in the homework 1 instruction, for multiple commands with `execvp` need some command string parsing. `execvp` is the system call, which is used when the numbers of arguments for a program to be executed is dynamic. 

You can think of parsing and looping of `execvp` but as professor mentioned, once `execvp` runs, the rest of your program won't be executed. That's why we need `fork()` function to make independent child processes.

**Comment by DustinPham** [comment]
Also, I am getting an error that just prints out only "Command terminated". 
Is that error having to do with execvp?

**Comment by mikeizbicki** [comment]
`perror` will never print the error message `Command terminated`, so I don't understand what your problem is.

**Comment by tkimva** [comment]
I need more detail for this question. The error meesage seems to be weird.

**Comment by DustinPham** [comment]
"Command terminated" happens why I try to do:
echo "hello"; ls
It echos "hello" but then says "Command terminated" soon afterwards. I believe it does this whenever I try to chain multiple commands.

**Comment by hgarc014** [comment]
I recommend having print statements so that you know what is being passed in. I assume you are either passing in the semi colon or white space after a command.

**Comment by tkimva** [comment]
Or you can simply trace the variable with GDB
