### ISSUE TITLE
Hammer vs Well 

### ISSUE THREAD

**Issue by holidaylvr** [mikeizbicki/ucr-cs100#280]
When I run my program on Well my code runs the different cmds fine for the most part (excluding my bugs). But when I switch to Hammer, my code breaks down and only certain cmds will work. Am I doing something wrong? When I switch to Hammer I see a lot of "execvp: bad address". I saw the post earlier concerning null termination but why would this be an issue on Hammer and not Well?

**Comment by mikeizbicki** [comment]
`hammer` and `well` are two different servers with different configuration settings.  If your program has a bug, it might work under some configurations but not under others.  In your particular example, when `well` starts executing your program, you get lucky and it just so happens that there is a `null` in memory at the correct location to make your code work.  When you run the same program on `hammer`, however, that `null` value is not in memory and so your code doesn't work.

A good practice when developing software is to test your programs on many different environments.  This makes bugs easier to find because each environment will find different bugs.
