### ISSUE TITLE
To prevent deprecated conversion warning

### ISSUE THREAD

**Issue by tkimva** [mikeizbicki/ucr-cs100#282]
For your homework, you have to compile the code without any warnings. Here is one tip.

In our repository, one of the lecture examples [exec.cpp](lecture/exec.cpp) generates this warning with GCC 4.8. It would be a good practice to learn how to remove the warning.

If you compile the code, then you will see the following warning from GCC 4.8 because GCC 4.8's default compilation options are different than GCC 4.1 (well.cs.ucr.edu) because `-Wwrite-strings` is active by default.

```
argv[1]= "-a";
argv[2]="-l";
```

```
warning: deprecated conversion from string constant to ‘char*’
warning: deprecated conversion from string constant to ‘char*’
```

To remove this warning you can do casting

```
argv[1]=(char*)"-a";
argv[2]=(char*)"-l";
```

or you can change the GCC compilation option. you can compile with the following option

```
g++ -Wno-write-strings filename.cpp
```

**Comment by mikeizbicki** [comment]
The code must be compiled with the `-Wall` and `-Werror` flags, so `-Wno-write-strings` is not allowed.  

Also, while the suggested type cast succeeds in eliminating the compiler warnings, it results in the potential for segfaults.  In class, we showed how to use the `strcpy` function to copy a `const char*` into a `char*`.  This method will always work and never cause segfaults.

So because this issue might confuse students, I'm closing the issue.

**Comment by tkimva** [comment]
I see.

**Comment by tkimva** [comment]
@mikeizbicki Then you intentionally made the problem in exec.cpp? which I didn't know it.
