### ISSUE TITLE
Signing Grades

### ISSUE THREAD

**Issue by hgarc014** [mikeizbicki/ucr-cs100#307]
@mikeizbicki  @tkimva 

have you guys been signing grades correctly for students?? All my grades have a [bad signature]. I also did a little checking (wrote a script) and it seems everyone's grades have a bad signature.

**Comment by tkimva** [comment]
As I know, It's known issue. Even it happened to me as bad signature when professor graded. I already reported to professor a few weeks ago.

**Comment by tkimva** [comment]
anyway, thanks

**Comment by hgarc014** [comment]
no problem. I wasn't sure if you guys were aware or not.

**Comment by mikeizbicki** [comment]
If you want the signatures verified, you have to install the instructor encryption keys.  They are located in the `people/instructors` folder just like your information is in the `people/students` folder.  There is a script called `install-instructor-keys.sh` that should install them for you.  (You must have a `gpg` installed for the script to work.)

I have it the keys installed on my machine, so I can check if grades have been tampered with.  But it's not strictly necessary for you to install them as well.

**Comment by hgarc014** [comment]
I see,thanks

**Comment by tkimva** [comment]
@mikeizbicki the issue what I meant above is that there is still bad signature issue even if I run `install-instructor-keys.sh` We saw this issue together first week in WCH110 when I generated my GPG. It's still same as follows even if I run the script again to install your gpgkey. I know it's not necessary for students but I think I have to let you know at least to fix this issue if there is any bug.

---

```
 10 /  10    |  lab0-vim                       |  Mike Izbicki [bad signature]
 10 /  10    |  lab1-git                       |  Taeyoung Kim [signed]
 10 /  10    |  lab2-fork                      |  Taeyoung Kim [signed]
```

---

Did anyone has the same issue?

**Comment by hgarc014** [comment]
I had the same issue. I have bad signature for both of you guys after installing the instructor keys and creating a GPG. I haven't looked into this, but I assume it has partially to do with the private key or mike having multiple keys. I think I saw multiple keys for Mike.

**Comment by mikeizbicki** [comment]
@hgarc014 Henry, if you're interested in looking into this, figure out what's going on, and submit a patch, I'll give you +100 pts extra credit.

**Comment by hgarc014** [comment]
I'll see what I can do.

**Comment by Liniarc** [comment]
I believe the issue is that the private key you used to sign doesn't have its corresponding public key in the people/instructor file. The key ID of the signature Mike used to sign the keys is D2820CEC, but none of Mike's keys in the repository have that ID. 

If Mike runs `gpg --list-keys` and sees a key with D2820CEC, then that key is probably locally in your keyring but never uploaded in the git repository.
There's really nothing we could do to patch it since there's no way for any of us reverse engineer your keys. 

I think you could solve the problem by running 
`gpg --output "./people/instructors/mike@izbicki.me" --export "mike@izbicki.me"`
and overwrite the current file with one that has the correct keys.

Alternatively, you could change your git config settings using
`git config user.signingkey "existingKey"`
where existingKey is one of the key ids already in repository (6EFDDC2A, 49EE4745, 82FF367F)
This however will still show "bad signature" when checking the logs. (And assumes you still have those keys in your secret keyring and know the password to them)

P.S. after installing the instructor keys, I get good signatures from Taeyoung

**Comment by mikeizbicki** [comment]
The key was generated and added into the repo using the `addgrader` script in the `scripts` folder.  The script is rather ad-hoc.  I never bothered to make it robust because it gets run so infrequently.

A correct patch would do two things:
1. It would update the `addgrader` script to ensure that the correct public keys get added into the repo, and that the local git configuration is set to use the corresponding private key.  I think the issue is somehow being caused by the fact that I already had several keys on my machine.  A _really_ good patch would let me generate keys on multiple different computers, but this might cause extra issues.
2. It would update the `calcgrade` script to ensure that the public keys have previously been installed.  If they haven't been installed, then it would install them first.  This would ensure that the `[bad signature]` error message only occurs when it actually should.

There's a lot of things interacting here, and so there's probably a lot more than 100 points of extra credit to be had for a really nice set of fixes.

**Comment by Liniarc** [comment]
Just a note: Mike's key was added to the git repository on September 23th, and the `addgrader` script had a pretty severe bug that wasn't fixed till October 10th. (Although, it seems like it shouldn't have exported anything to the instructor folder)

 From what I can tell, `addgrader` currently should have been able to handle multiple public keys in the keyring
