### ISSUE TITLE
beginner -> intermediate vim

### ISSUE THREAD

**Issue by 2c2c** [mikeizbicki/ucr-cs100#338]
I'd like to make a couple example based casts on beginner to intermediate level vim

I would cover things like macros, recursive macros, visual block usage, word objects, regex search and replace, and random convenience keys I can think of along the way.

**Comment by mikeizbicki** [comment]
This sounds like a great topic.  Do you already have the setup to make videos like this?

**Comment by 2c2c** [comment]
Ya I stream games so the setup is kind of similar. Unfortunately linux doesn't have any good keyboard input programs (none as good as the mac one on vimcasts anyways). But I found one and it works. The other issue was that my PC's fan is irritatingly loud, but I just tested an audacity noise removal plugin and it works really well

**Comment by 2c2c** [comment]
https://www.youtube.com/watch?v=YI8UY00MC_I&

I was going for something like this. It's one take/unscripted though but came out pretty well. Given this sample I guess I want to know 1. how many of these types of videos would you be looking for to meet expectations of HW4 and 2. if you think I should not 'just wing it' and follow a script of some sort

**Comment by mikeizbicki** [comment]
Comments:
1.  Adjust your screen resolution so I can read what you're typing in vim
2. It's hard to hear what you're saying.  Somehow you need to get the volume louder.  I stopped watching after about 2 minutes because I just couldn't figure out what you were saying.
3. I _really_ like that key press program
4. There's a lot of "down time" in the video where nothing is happening.  I think the videos would be much better with a bit of editing to remove this.
5. It's not clear to me what you're going to go over, so why should I watch it?  I like the example choice you did.  I was planning on doing something similar in class actually, but we ran out of time.
6. I think shorter, more focused videos would be better.  I'm at least a lot more likely to watch a 3 minute video that clearly states in the first sentence "we're going to cover the basics of macros" or "we're going to combine macros with buffers" or something like that.  That way I know what I'm getting into and can figure out if I want to watch it or not.
7. I would much rather have few high quality videos than lots of lower quality video.  I'd say 4 videos, each 3-5 minutes, that are clear, fun, and engaging would be an A on the assignment.  You should also give them a simple html page something like what Rashid and Kyler's video tutorial did last time.  It can be hosted on my website or someplace else if you prefer (unfortunately, github markdown doesn't support embeded video).  It doesn't need a lot of text, just enough so that people can figure out what videos to watch.

**Comment by 2c2c** [comment]
the video I posted goes over 3 core concepts. I can likely break that into individual videos using the same example and do something else for a fourth (I considered plugins but a lot of others are going in that direction)

**Comment by 2c2c** [comment]
all points have been addressed:
1. fixed vm's output resolution
2. raised the mic
3. got a way better key press program (the quality on this one is probably good enough for you to use in class the first week when you're going over vim)
4. cut the downtime
5. objective more clear
6. way shorter
7. wow! exciting

take 2:
https://www.youtube.com/watch?v=gngmD-mFMhc&vq=1080p

edit: alright forgot to say 'we will be going over text objects' unfortunately. ignoring that, feel free to comment

**Comment by 2c2c** [comment]
@mikeizbicki paging for comment. goal is to finish hw4 rather early so I can focus on my other classes

**Comment by mikeizbicki** [comment]
Much better.  I'd say you're somewhere around the 80-90 percent mark right
now.

Comments:
1.  You still need to make the text bigger.  You have all that empty space
   in the video not being used that could be filled with larger characters.
2. You never actually explain what the command `ci)` or any of the others
   is doing step by step.  In particular, the verb is `c`, but the range that
   we're applying the verb is `i)`.  This is a particularly confusing range
   because it has the letter `i` in it which normally means insert mode but
   here has nothing to do with insertions.  If it were me, I would spend 15
   seconds saying something like: "Remember that every command in vim can be
   modified to adjust how the command works.  `d)` for example will delete
   from your current location to the end of the next parenthesis."  Then "But
   often you want to delete everything in the parenthesis, in that case, use
   `di)`.  Notice that the `i` doesn't send me into insert mode.  If I do want
   to enter insert mode, I should use the `c` command instead.  It's just like
   `d` but puts you in insert mode afterward."  Something like that.
3. You're c++ code doesn't actually compile, so why are you making c++
   code?  Also, don't assume you're viewers are in cs100 by saying things like
   "the sizeof quiz".  Instead, just say "we're going to write a program that
   will print the sizes of different types".  That makes it so anyone watching
   the video can follow along.  If you stick a few couts in there and some
   text in `""` then you can do all of your examples right in the c++ code.

**Comment by 2c2c** [comment]
I'll crank the font up to something like 18 or 20 and see how you like it (i thought you just meant the res scaling was bad)

i contemplated going over explaining the i part of text objects, but then I feel obligated to talk about using a in text objects e.g. ca), da}, etc. i'll do it but i expect it to run over 4 minutes.

The first video shows from start to end what I want to do (the code will compile only by that point). The issue is that it was too long-- So I'm instead doing the same thing, but separating one 'concept' per video. The video afterwards picks up from the same spot as I left off in the last. That's the plan anyways. 

I'll make a take3 tonight

**Comment by mikeizbicki** [comment]
I think talking about `a` at the same time would be fine even if it takes a
bit more time.

It's fine to have it extend over multiple videos, but it should still be
self contained.  And it's not like adding `cout` in front takes any extra
time.

**Comment by 2c2c** [comment]
@mikeizbicki 
Font is higher (If i go anymore I'll have word wrapping issues in the later installments)
Elaborated much more on the verbs, a, i in textobject context

https://www.youtube.com/watch?v=jsdm_lVBuwk&

sidenote: I emailed you regarding a grade exploit

**Comment by mikeizbicki** [comment]
I think the content of this video is excellent.  Also, the layout and everything else looks great now.  Your grade would be at least a 90 with videos like this.

Some minor nitpicks on how to improve:
1. You use a lot of filler words like um.  Editing these out would make the video a little easier to watch (and probably ~20 seconds shorter).
2. Occasionally your quiet while you're doing something rather important on the keyboard.  For example, when you paste material into the right panel, you don't say anything while your fingers are doing the pasting.  It was easy for me to figure out what was going on, but it would be a little easier to follow if you just said "I'm pasting an example right now" or something.
3. Your voice is a little hard to hear.  With the volume all the way up I had to really focus.

Again, this looks great, and those suggestions are pretty minor.  There's no need to redo this video unless you really want to.  Just keep these things in mind for the next ones.
