### ISSUE TITLE
Hw4 vimrc

### ISSUE THREAD

**Issue by atan009** [mikeizbicki/ucr-cs100#340]
I'd like to work on a vimrc tutorial along. hfanc001 would like to work on this as well.

**Comment by luizlopezm** [comment]
are you looking for other partners because I was planning on doing vimrc also

**Comment by mikeizbicki** [comment]
This sounds like a great topic, and I think there's room for (at least) 3 people to work on it.  

My recommendation is that you select about a dozen or so vim plugins that you think will make life easier for cs100 level students.  Then you create a prebuilt vim configuration (inside your own new github repo).  The tutorial would then be on three things:
1. instructions for how to install your "vim distribution".  
2. instructions on how to use the features provided by your distribution. This should include animated gifs demoing the features.  Lots of plugins have these already, or you can [read these instructions](http://unix.stackexchange.com/questions/113695/gif-screencasting-the-unix-way) on how to create them.
3. instructions on how to make minor tweaks to the distribution

If you do this well, I'd like to modify lab0 so that all the future cs100 students will use your distribution and work through your readme as part of the lab.

**Comment by 2c2c** [comment]
I'd like to know what plugins in particular you guys want to cover (I use plugins and won't have to explain some of the magic if it's covered in yours).

Sidenote: plugins like gitorious are considered really nice and convenient, but the abstraction kind of hampers learning the underlying git commands were you to be introduced to it early enough. Since learning git is a primary goal of the class I thought I would just throw that out there.
