### ISSUE TITLE
Linux Installation Tutorial HW4

### ISSUE THREAD

**Issue by DustinPham** [mikeizbicki/ucr-cs100#351]
@yli082 and I would like to do a tutorial on how to set up a dual boot of a Linux installtion on Windows and also how to set up a Virtual Machine on Windows should people prefer to do that instead.

**Comment by mikeizbicki** [comment]
I suspect this is not a great idea for two reasons:
1. There are already hundreds of these tutorials online for any distribution you can name.  What would your tutorial provide that these tutorials don't?
2. Installing an operating system has lots of complex edge cases.  Just because the procedure you describe works for your machine, doesn't mean it will work for someone else.  For example, they may have a new type of wireless card that needs special installation instructions.  Covering all these edge cases would be a LOT of work.

If you can address these two issues, I'll approve this topic, but my recommendation is to find something else.

**Comment by DustinPham** [comment]
Will find something else to do.
