### ISSUE TITLE
Tutorial on github to contribute to open source <HW4>

### ISSUE THREAD

**Issue by hgarc014** [mikeizbicki/ucr-cs100#359]
This would cover things like:
forking, cloning, editing and pushing, pull requests, and upstreams

**Comment by drami025** [comment]
I would like to do this too.

**Comment by mikeizbicki** [comment]
How would this be different than lab1?  Why would a student want to read your writeup instead?

**Comment by hgarc014** [comment]
We were thinking of adding to lab1:
-  upstream (how it works, how to use it, how it differs from origin)
-  a terminal game on git commands (that will allow practice on git commands and usage)

**Comment by mikeizbicki** [comment]
Both of those sound interesting, but I'll have to see them fleshed out a bit more in order to determine if they'll work or not.

**Comment by ChemicalWonders** [comment]
I would like to contribute to this, however, I would like to add : 
Teaching people about remotes which would include the differences between SSH-ing into GitHub and adding secure keys vs HTTPS commands vs using Subversion to check out the Git Repository.

This in turn will help them learn the following: 
Instead of re-cloning the git repository, being able to fetch the upstream of a repository and merge it into their fork in order to get a current working version.

Dealing with several branches and tags at a time. Making sure they know what the difference between a tag vs a branch, and what they can do with each.

Last, I would like to add the different online git clients, and other versions of Version Control that they could try out, and I would have basic information on them, as I don't know them very well either.
