### ISSUE TITLE
Hw#4: Cppcheck

### ISSUE THREAD

**Issue by lpeng003** [mikeizbicki/ucr-cs100#373]
I would like to do hw4 on cppcheck. The idea is to create a tutorial on cppcheck to cover its features and how to use it.

**Comment by horventsai** [comment]
I would like to work on this issue as well.

**Comment by khiguera** [comment]
I would also like to work on this.

**Comment by Adamantly** [comment]
I would also like to work on this

**Comment by mikeizbicki** [comment]
cppcheck is a rather simple tool.  I doubt there's enough material there for four people to work on.  You'd have to provide me a rather detailed outline before I approve.

**Comment by khiguera** [comment]
We were thinking on doing a tutorial on cppcheck and also a comparison with other debugger tools such as gdb and valgrind. Also, provide concrete examples on when it would be better to use one or the other to more efficiently find and debug certain bugs. In other words, we would be doing a tutorial in detail for cppcheck while showing the advantages for certain cases against the other tools.

**Comment by mikeizbicki** [comment]
What **specifically** are the advantages and disadvantages you would cover?  What **specific** examples would you use?

**Comment by khiguera** [comment]
Specific advantages and disadvantages would be like what you briefly mentioned in class where cppcheck is able to catch certain bugs but other bugs it will not catch. We would go more in depth in those cases and show those examples of when cppcheck will compile and say there are no bugs but there are in fact bugs that it simply did not catch that another tool would be able to catch. I do not recall the specific code and bug as an example right now off the top of my head, however I recall you showing us one example in class. We would go into more detail into cases such as those and show cppcheck not catching those bugs and then using another tool to show the bug is in fact there.

**Comment by mikeizbicki** [comment]
Read more about exactly what types of bugs cppcheck can find, and how it finds them.  I won't approve this topic for four people until you have a specific outline of things you want to discuss.

The danger with this topic is that you will be too vague and handwavy.  You really need to dig into the specific details of how cppcheck works.  This is potentially a confusing topic, and I want to make sure you're all ready for it.

**Comment by Adamantly** [comment]
We would like to discuss how cppcheck can find bugs such as memory leaks, resource leaks, stylistic and performance errors, memory duplication etc and how it can be used in conjunction with runtime debuggers such as GDB, and memory-checking debuggers such as Valgrind. We would also discuss the advantages of how a static analysis tool such as cppcheck can improve one's source code and how cppcheck does detect bugs that normal compilers do not detect (such as syntax errors). We would also talk about the disadvantages of only using the cppcheck with the normal compiler without using it in conjunction with other debugging tools.
