### ISSUE TITLE
HW #4: Boost Library

### ISSUE THREAD

**Issue by atosti** [mikeizbicki/ucr-cs100#378]
I'm interested in the features offered by boost and want to create a text guide on how to use various functions within it, namely those not covered in class. Right now I'm looking into covering Lexical cast, Tribool, For-each, and possibly Tokenization, but I was wondering if there were other functions within Boost that would be recommended for me to cover.

**Comment by mikeizbicki** [comment]
Sounds good.  I'm not super familiar with boost, so I can't provide specific recommendations about what to cover.  But it would probably be better to be very thorough about one specific boost library than superficial about many things.

If you do decide to do the boost tokenizer, you should work with Dave (#365) who is doing strtok.  I think it would be really cool to have a side by side comparison of the two approaches.

**Comment by hray001** [comment]
I was planning on covering boost as well except covering boost's heap, hash, as well as boost's filesystem as an alternative way to use paths and iterating through directories. I wanted to focus more on the data structures under boost as a clarification for those who might feel uncomfortable still with data structures after CS14. Filesystem I wanted to cover because of how it can be used for rshell with ls and dealing with directories.

**Comment by mikeizbicki** [comment]
@hray001 Talking about a few data structures under boost would be great!  The best way to do this would be to think of an example that uses them, and explain the example.

I think talking about boost's filesystem features is not a good idea, because we want students to use the unix libraries.  Did you use boost instead?  If so, it's okay since I didn't specifically forbid it, I'm just curious.

**Comment by hray001** [comment]
No, I didn't use boost's filesystem since stat was needed for all the information in ls -l. I just saw filesystem as another possibility for iterating through directories. If I found a way to obtain all of the information stat has from filesystem I would have used it instead.
