### ISSUE TITLE
For Hw1, stat call fails.

### ISSUE THREAD

**Issue by jinsongwei** [mikeizbicki/ucr-cs100#396]
When I run ls -R. I can access to the current files by using "stat(file, &buf)". But after opening another directory which is in the current directory, it can not be accessed by "stat(file, &buf)" at all. It returns -1.
Could you explain why calling stat fails?
Thank you !

**Comment by tkimva** [comment]
You haven't given us enough information to help you

`man 2 ls` shows the type of error as `errno` when -1 is returned on error. Please try to see the detail with errno and use GDB to check the function parameter of `stat`

**Comment by tkimva** [comment]
reopened as closed by mistake

**Comment by jinsongwei** [comment]
Thank you! I found the bugs.

**Comment by tkimva** [comment]
Great!

**Comment by jesuscreyes** [comment]
I think I'm encountering a similar problem in my program, and have been unsuccessful trying to solve it.

Could you explain what the bug was for you and how you fixed it please?

**Comment by gbrlrz017** [comment]
@jesuscreyes , If you haven't solved your issue yet: 
I had a similar problem, and this was the output when I ran with `ls -R` : 
     .:
     README  LICENSE  Makefile  src  tests  bin  
     ./src:
    cannot access rschell.cpp
    stat: No such file or directory

For my code, that meant that the sub directory opened, but stat failed when calling `stat("rschell.cpp", ...)` . The fix (for me) was to prepend the parent directory/path to `rschell.cpp` , so calling stat would look like `stat( "./src/rschell.cpp" , ... )` 

I'm assuming this is because a call to stat assumes you are in `.` instead of the sub directory. 

Hope this helps!

**Comment by jesuscreyes** [comment]
@gbrlrz017, I think that's the exact issue that I have. I'll try to implement it, and hopefully it works.

Thanks!
