### ISSUE TITLE
HW3: Clarification of the PATH environment variabl

### ISSUE THREAD

**Issue by abarb014** [mikeizbicki/ucr-cs100#481]
Say `usr/bin` is in the `PATH`. When `execvp()` gets called I know that it searches the `PATH` for the program, but does `execvp()` look in both the `usr` and `bin` directories, or solely `usr/bin`?

After looking at my own `PATH` variable, I saw that it has many directories that start off at `usr`, and it seems awfully redundant to search one directory over so many times, so I've just been assuming that all `execvp()` looks into is each path in `PATH` that is separated by colons, and NOT each individual directory.

Also, should our program seach the root directory for the executable? I couldn't find anything on whether or not `execvp()` does, but again I'm assuming it doesn't search the root directory because a single forward slash isn't in my `PATH` variable.

Thanks!

**Comment by mikeizbicki** [comment]
First, you probably meant `/usr/bin` instead of `usr/bin`.  These are very different paths!

Second, `execvp` only looks in the directories listed in the `PATH`; it does not look in any subdirectories/ancestor directories.  This would be easy to test by creating executables `/usr/bin/asdasdasda/myexec` and `/myexec` then trying to run those executables in bash.  Typing just `myexec` would get you a "command not found" error.

**Comment by Dave864** [comment]
So are we to do the same thing as `execvp`, only look in the directories listed in the `PATH`, or do we need to look in both the directories and subdirectories in `PATH`? From the assignment specs I assumed that we look in just the directories, but after reading this response I am nout so sure anymore.

**Comment by mikeizbicki** [comment]
@Dave864  Look in just the directories listed.

**Comment by 2c2c** [comment]
since this is the only relevant thread regarding PATH: you should definitely check if your shell is working on hammer for this assignment. there's some funky directories that don't actually exist in the remote PATH. depending on how you handle those kind of errors you may never actually open programs (which is probably terrible for your grade).
