### ISSUE TITLE
Valgrind possibly lost memory

### ISSUE THREAD

**Issue by yli082** [mikeizbicki/ucr-cs100#492]
Will we have to fix possible memory leaks due to child processes for this coming assignment? Also, will cd have to work with piping and connectors?

**Comment by mikeizbicki** [comment]
1.  I don't care if there are memory leaks in the child processes.  It's only your parent rshell process that needs to be leak-free.
2. `cd` should behave exactly like bash's `cd` command with regard to i/o redirection and piping---since it doesn't use stdin/stdout, this should be trivial.  With regards to connectors, `cd` should exit successfully if the pwd was changed and should fail if the pwd was not changed.  This is a relatively minor detail, though.

**Comment by aorti017** [comment]
How would you determine if a possible memory leak reported by valgrind stems from a child process?

**Comment by mikeizbicki** [comment]
Valgrind has an optional parameter `--trace-children` that can be set to
`yes` or `no`.  The default is `no`, which means do not enter into `exec`
syscalls.  That means if there is a memory leak in `ls`, for example, it
will not get registered as a memory leak in your `rshell` program.

So basically, you just have to run valgrind like normal.
