### ISSUE TITLE
hw#3 issue with make command

### ISSUE THREAD

**Issue by ChemicalWonders** [mikeizbicki/ucr-cs100#500]
For some reason, when I run my rshell, I cannot get my "make" command to work completely. 

It will complete the first line, but when it tries to run g++ on the others, it tells me that I have linker problems. If I specify this as a bug, will that be bad?

**Comment by mikeizbicki** [comment]
You should be able to run `make` from within your shell.  Since you haven't described the actual commands you ran or the error messages, there's no way for me to guess what the problem might be.

**Comment by DustinPham** [comment]
I have the same problem, but with g++:

```
g++ -Wall -Werror -ansi -pedantic src/main.cpp -o bin/rshell
make: g++: Command not found
make: *** [all] Error 127
```

**Comment by ManjunathChet** [comment]
I have a similar issue as well. After running the following test, I believe the error is caused by how we define our PATH;

Makefile is a script that runs g++. To mimic this, I wrote a dummy script with a random process in it. I ran;

`touch execute_cmd.sh` #creates a file called execute_cmd.sh
`chmod u+x execute_cmd.sh` #makes the file an executable

Then in vim, I made the script contain;

```
#!/bin/sh
echo HELLO
tar
```

So the script has `tar`. If you're finding PATH correctly then when you run
`execute_cmd.sh` in your rshell, you should get an output that looks like this;

```
HELLO
tar: You must specify one of the `-Acdtrux' or `--test-label'  options
Try `tar --help' or `tar --usage' for more information.
```

If you are finding PATH incorrectly, then when you run
`execute_cmd.sh` in your rshell, this will happen;

```
HELLO
./execute_cmd.sh: line 5: tar: command not found
```

The "command not found" error is the same we're getting in regard to g++ and makefiles. This is why I think it's an error in how we define our PATH.

**Comment by ChemicalWonders** [comment]
whoops, i accidentally deleted my comment. -___-''

I was trying to edit it so that my code was readable. 

basically, I had:
`/class/classes/kchan039/Documents/rshell`
`kchan039@hammer.cs.ucr.edu$ make clean`
`rm -rf bin`
`make: rm: Command not found`
`make: *** [clean] Error 127`

The same thing happens with my g++ if I make more than one file. The first one will work, but the subsequent ones won't.

**Comment by hgarc014** [comment]
The reason for clean (in your case) giving you a error (what Thomas and i found) is that you are attempting to delete the executable that is currently running. If you move rshell outside of the bin folder and then make clean it should work correctly. As for g++ giving an error it may be something similar, but mine works and I haven't found an error with g++ in make.

**Comment by ChemicalWonders** [comment]
so I guess I'll just report it as a bug, and hope for the best then. :P
