### ISSUE TITLE
Grade change by pull request vulnerability?

### ISSUE THREAD

**Issue by ChemicalWonders** [mikeizbicki/ucr-cs100#508]
So I was playing around with the grades, and I realized that you can figure out someone's grade by entering their name with the shell script calcgrade.sh. This part is normal.

However, since you have writing capabilities to your own repository, you can essentially pull request from someone else's repository, unless it is private, to write to your own repository. Since we all forked from the same repository, all of them show up on GitHub and are available for view. 

You can essentially change your grade by pulling someone else's grades into your repository. This can be done through the Github GUI. Then we could just write a fake commit message saying "Merging branch from b123125 to d123123". The only problem is that these are not signed, but with calcgrade.sh, even with installing the keys, Mike's commits are still showing up as unsigned. 

I was going to experiment with it more, but I wanted to let Mike know about this first.

**Comment by Liniarc** [comment]
Mike's keys are unsigned because his public keys are not in the repository. As such, we can't install them and verify his signature. However, I'm under the impression that Mike still is signing his commits with his private key and is able to verify them with his public key on his own computer.

**Comment by mikeizbicki** [comment]
@ChemicalWonders Good work!  You haven't quite identified a vulnerability, but you're getting really, really close.

To claim the full 200 pts extra credit, you'll have to: 
1. provide the exact sequence of git commands you need to run to change the grade (100pts); you may not rely on the github interface at all
2. show how to fix the scripts to fix this vulnerability (100pts)

If you have any questions, or think you have a solution to the steps above, please send it to me via email (mike@izbicki.me) so that it's not public before it's fixed.

**Comment by 2c2c** [comment]
I've tinkered around and I'm fairly sure you could make this undetectable
from scripts alone. I don't want to claim as my grade is high enough

**Comment by 2c2c** [comment]
ok well thats wrong on second thought but the exploit is real and it would require a script that does much much more than what it does currently to fix
