### ISSUE TITLE
git-game

### ISSUE THREAD

**Issue by hgarc014** [mikeizbicki/ucr-cs100#642]
Daniel and Henry's git-game.
Here is the repository for git-game: https://github.com/hgarc014/git-game.git
command to clone the repository:
`git clone https://github.com/hgarc014/git-game.git`

**Comment by mikeizbicki** [comment]
When you say:

> NOTE: Any executables in this game were compiled in linux. Therefore, they are unlikely to work on other platforms.

this makes me think you have executables in the git repo?  This is never acceptable for two reasons:  First, git can only efficiently store text files.  Second, executables are not even remotely portable.  If you compile something on hammer, for example, it will not work on well; it must be recompiled.  Every version of every library must be exactly the same in order for one binary to work on two separate computers.  We always distribute source code so that the user can compile the code to work with whatever libraries they currently have installed.

Fix this (and check my pull request) then I'll run through it.

**Comment by hgarc014** [comment]
Yes, we know. We didn't want people to view the executable to find the answer. I think I have a simple solution, though...

**Comment by mikeizbicki** [comment]
then why is the executable even in there?

**Comment by hgarc014** [comment]
The point of the executable was to check if the "player" has actually merged the two branches.
