### ISSUE TITLE
git-game fixed executable issue

### ISSUE THREAD

**Issue by hgarc014** [mikeizbicki/ucr-cs100#646]
I fixed the issue with having a compiled executable...

Daniel and Henry's git-game.
Here is the repository for git-game: https://github.com/hgarc014/git-game.git
command to clone the repository:

```
git clone https://github.com/hgarc014/git-game.git
```

**Comment by hgarc014** [comment]
@mikeizbicki  Would you like us to add the git-game link to the git lab references and create a pull request?? https://github.com/mikeizbicki/ucr-cs100/tree/cs100-2014fall/assignments/lab/lab1-git

**Comment by mikeizbicki** [comment]
Problem 1: The prompt says:

> Your first task is to checkout the commit whose commit message is the answer to this question ...

But it doesn't tell me what to do afterward.  You need to explicitly tell me that the next clue is in the README file.

Question 2:

This is a really ugly way to structure your writing in the README:

> We want to get to a branch who's name is the answer to 
> this riddle: I am a creature that is smaller than man, 
> but many times more in number. In code, my appearance 
> can be subtle and no matter where I am found, I am unwanted.

Much prettier is:

> We want to get to a branch who's name is the answer to this riddle: 
> I am a creature that is smaller than man, but many times more in number. 
> In code, my appearance can be subtle, and no matter where I am found, I am unwanted.

Good programmers fall into two camps with how they write their plaintext documents.  Some programmers put each paragraph on a single line; they only hit enter once per paragraph.  This is much like you would type in a WYSIWYG editor like Word.  Others (like me) hit enter at the end of each line.  Both of these styles make modifying and viewing diffs between files pleasant, which is why they're used.  No one splits a sentence in the middle of a line to create "pretty paragraphs" like you are doing throughout your writeup.  It makes lots of git's features super awkward to use.  Lots of people are doing this, and it's my fault for not mentioning it in class.  But if I were a random internet person and stumbled onto this, I would be immediately suspicious because of this writing style.

Also, there's a grammar mistake in your version.  

Question 4:

It's a bit annoying that you have all that unrelated junk at the top of the `.gitignore` file before I get to read the important bits.

There is no such thing as an "abstract data structure."

Your text says:

> the executable "outputclue"

but this file does not exist.  There is a shell script (the noun "executable" idiomatically refers only to binary files) called outputclue.sh.

This: 

> then you should try resolving a conflict between this branch and code4life

makes no sense.

`mouse` question:

When I run diff on the files, the output isn't really any easier to parse than just the files themselves.  It would have been better if the files were 100000 lines long or something.

Henry question:

Why is the keyboard information not in the Henry branch?  Why tell me exactly what command to type?

keyboard:

You lied to me!  You said it was the keyboard branch that needs updating, but it's not! It's master!

It probably would have been better if the other git repo was a fork of this repo in Daniel's account.

Why is this causing a merge conflict?  That's a confusing way to end.

---

Overall nice.  I hope future students get a kick out of it :)  

Some of my comments are easily fixable, some aren't, and some maybe shouldn't be fixed.  Fix whatever you want and submit the pull request like you suggested, then I'll give you the grade.  Make sure to tell me what you fixed in the pull request.
