### ISSUE TITLE
waitpid(int *status)

### ISSUE THREAD

**Issue by willccoates** [mikeizbicki/ucr-cs100#83]
im trying to use this like mike said in office hours, but its complaining that i am not using the waitpid with three parameters, im confused how to fix this

**Comment by mikeizbicki** [comment]
Was there something on the man page that wasn't clear?

**Comment by willccoates** [comment]
well when i call fork i assign it to a
pid_t variable and i try to call waitpid on that pid_t variable, i looked at the man page and it said an int\* should go in there but in office hours i thought it was the pid_t, im just confused about that

**Comment by mikeizbicki** [comment]
The man page explains what all three parameters do.  A lot of people have spent a lot of time making the man page documentation very detailed.  _Read it all_.  If you have a specific question about what something in the man page means, we can talk about that.  Otherwise I'm not going to answer your question.

Also, the lack of proper spelling, grammer, and formatting indicates that you haven't put very much thought into your question, and so I'm not going to put very much thought into an answer.

**Comment by willccoates** [comment]
ok then, i am sorry

**Comment by DanTheTingler** [comment]
Will, I'm not too sure if this is very helpful, but try using just wait() instead of wait_pid(). I don't think I used waitpid in my assignment at all, so maybe wait() will do just what you need it to do. Goodluck!
