### ISSUE TITLE
Can't run rshell in scipt

### ISSUE THREAD

**Issue by AndyThio** [mikeizbicki/ucr-cs100#851]
When I run rshell in a normal terminal, it works perfectly fine. However when I start a script and attempt to my rshell it gives me a segfault right away. I ran gdb during the script to find the segfault and it's pointing to a function that is not in my code. I'm typing `script` then `make` and finally `./rshell`.

**Comment by mikeizbicki** [comment]
This means that your program had a bug in it the whole time, but the bug just wasn't triggered until you ran the `script` program as well.  Unfortunately, you haven't given us enough information to help you figure out where the bug might be.  The first thing to check is that you're properly doing error checking on all your syscalls.  One of them might be failing when you're assuming it succeeded.

I like that you tried to use gdb to find the problem.  We will be covering how to use gdb in more detail in the future, and in particular why gdb sometimes tells you the problem is in someone else's code when it's actually your own.  In the mean time, you can look at the `textbook/tools/gdb` folder for more clues on how to use it.  In particular, look up the `backtrace` command.  It will tell you which one of your functions is calling the function that triggers the segfault.  It may also help to use the `step`/`next` commands to walk through your code line by line to see which ones trigger the segfault.
