### ISSUE TITLE
HW4 Proposal: Android ROM Development

### ISSUE THREAD

**Issue by shawnjzlee** [mikeizbicki/ucr-cs100#877]
## Project Overview

This project is a ROM focused on the increase in performance while conserving as much power as possible.
We aim for this project to eventually support multiple devices.

Initial testing / development on Google Nexus
## Purpose / Goal
1. Custom Android kernel based on [CyanogenMod](http://download.cyanogenmod.org/):
   - to allow overclocking
   - limiting number of background applications to save power
   - ARM optimization 
2. Create a minimalistic UI on Android Platform 5.0 (Lollipop):
   - Support the use of `.gif` wallpapers (may be turned off to conserve power)[experimental]
   - Custom system animation
   - PIE Controls (as default controls)
   - Build our own home launcher
## Education Goals / What We Hope to Learn
1. Licensing of open-source code
2. Utilize ~~all~~ most feature in git/GitHub
   - tagging (multi-version support)
   - branching (multi-device support)
   - distribution
3. Understand [Android Core Technologies](https://source.android.com/devices/tech/index.html)(e.g. Kernel, ROM)
4. Learn Java 
5. Testing on OEM smartphones
## References / Similar Projects:
- [Cyanogen Mod](https://github.com/CyanogenMod)
- [AOSPA](https://github.com/AOSPA)
- [PAC-man ROM](https://github.com/PAC-man)
- [SlimRoms](https://github.com/SlimRoms)
## Current Team
- Andy Thio | [athio001](https://github.com/AndyThio)
- Shawn Lee | [slee208](http://github.com/shawnjzlee)

**Comment by linuxmotion** [comment]
I like the idea, there is much to ROM development though. I am/was a member of https://github.com/OMFGB which was a ROM from 2012. Most of the application layer of Android is written in Java, with the exception of some native libraries. The core systems are written in C++. I would suggest going with the second goal and expanding that, specificallly how using git would help when developing an application. Building a launhcer is no easy task, the generic AOSP launcher has more lines of code than the ls program had, and has the program in many more files.

**Comment by mikeizbicki** [comment]
Sounds fun!  I'll want to see some sort of basic prototype by the time the hw4 proposal is actually due.  This is just to make sure that you are staying on track since your project will be a bit more involved.

Comments:
- If your goal is to conserve battery, then you should be _under_clocking, not _over_clocking.  This is a pretty hot topic in both industry and academia right now.  So doing a good job on a project like this would be a great way to get a good first job or get into a good grad school, whichever you want.
- One of the goals of this project is to do something for other people, rather than just for yourself.  (In general, doing things just for yourself is great, but that's just not the focus of this project.)  So with that in mind: 
  1. What will be the distinguishing feature about your ROM that will make people want to use it?  You don't have to appeal to everyone, but there should be some group of people out there for whom your ROM is the best choice.
  2. Will you be pushing your changes back into the main CyanogenMod codebase?
  3. You'll need to have some sort of writeup documenting your project.  You need to decide exactly what aspects you want to write about.  Will it be a tutorial on how to make mods like this?  Will it be just plain documentation on how to use your mod?  Something else?

Anyways, sounds like a fun project!

**Comment by shawnjzlee** [comment]
#### Update: Goals, Features, and Plans of this Project

http://shawnjzlee.github.io/UnguidedROM/

Above is a link to our page in detail describing our plans with this project during and beyond W'15. Thank you!
