### ISSUE TITLE
Calcgrade.sh shows bad signatures 

### ISSUE THREAD

**Issue by MichaelUy** [mikeizbicki/ucr-cs100#905]
Instead of confirming that grades were committed by authorized graders, calcgrade.sh is showing "bad signature" readings for commits by Mike Izbicki and "signed but untrusted" for TA's.

![capture](https://cloud.githubusercontent.com/assets/6821567/5992029/2cb692f4-a9c9-11e4-95a1-250c23ca843b.JPG)

**Comment by mikeizbicki** [comment]
Good bug report!  

The reason this is occurring is because for some reason my public key is not getting installed when the script is run.  The TA's are, but mine is not.  I'll probably need you to help me debug this in person during office hours.  And that will certainly be worth some extra credit.

The reasons this is not a security vulnerability is because I have the keys installed on my own computer.  When I run `calcgrade.sh` it shows my changes as being signed, and your change as being unsigned. Securitywise, all that really matters is what it displays when I check it.

**Comment by mikeizbicki** [comment]
@MichaelUy627 I still need you to revert your grade file back to its original contents.
