### ISSUE TITLE
school terminal issue

### ISSUE THREAD

**Issue by mchu011** [mikeizbicki/ucr-cs100#907]
can't log on to hammer for some reason

**Comment by mikeizbicki** [comment]
Issues like this should always be reported to `systems@cs.ucr.edu`

**Comment by GitHubbubble** [comment]
If you're desperate to code (as I am) you CAN try {bell.cs.ucr.edu}. I cannot fully reccomend it as I know there's a suite of tools and features part of the cs100 package on hammer, and since we're all new its not very kind to practice potentially dangerous code on the regular servers, but if you absoultely need to get in that's one way.
