### ISSUE TITLE
Two extra credit opportunities

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/ucr-cs100#918]
1.  I did a quick search to figure out what language the original NES legend of zelda was written.  I thought it was C, but I can't find any references online.  If you find a good reference that explains what it's written in, post it here and I'll give you 5 pts extra credit.
2. I'm not going to have time to fix at the `checksyscalls.sh` script until Friday.  I'll give anyone +20 pts extra credit if you look at it for me and fix whatever's broken about it before I get a chance to do it.

**Comment by Origami-Killer** [comment]
Does it have to be specifically the original LoZ because I think almost all of the original NES games were written in the same language. I actually got started with computer science by hacking Super Mario World (http://www.smwcentral.net/?p=main) and later other SNES games and it was entirely ASM. I can't imagine that NES games would use a more advanced language like C, and then the next generation SNES regressed to assembly. This source says that the original LoZ was written in ASM but I'm not sure how reliable Yahoo Answers is https://answers.yahoo.com/question/index?qid=20111102193438AAnohrZ

**Comment by NisreenFarhoud** [comment]
According to this source where users talk in detail about the memory aspect of the code for NES games, specifically Legend of Zelda, they all state it is written in assembly language: http://www.quora.com/How-did-game-developers-pack-entire-games-into-so-little-memory-twenty-five-years-ago

**Comment by mikeizbicki** [comment]
@Origami-Killer That page is not about how the original programs wrote the games.  It's about how to edit games that already exist.  In that case, it doesn't matter what language it was written in; you're always editing the assembly.  Even today, when people hack games written in C++, they're modifying the assembly/machine code output by the C++ compiler.

@NisreenFarhoud I don't see anything about the code for NES games there (although it's long, so I might have missed it).  Most of the tricks they're talking about is the game data, not code.  Also, the Crash Bandicoot developer says they used C for PS1 games.  But this is the generation of consoles after the NES.

**Comment by NisreenFarhoud** [comment]
In the discussion one person said, "The answer is tight Assembly Language, of course!" and another one said, "Assembly writing - very efficient, ultra-compact code size." Those were the lines that I saw that referenced assembly language directly.

**Comment by ikim025** [comment]
One of the games from Nintendo 64, the legend of zelda, is written in C programming language.
http://n64.icequake.net/doc/n64intro/kantan/step2/index1.html
This describes that n64 games are written in C programming language.
