### ISSUE TITLE
Gitlearn Interface Question

### ISSUE THREAD

**Issue by vgarc018** [mikeizbicki/ucr-cs100#936]
I was thinking about our conversation on this project, and was wondering if it is possible to replace the server with an already existing open source server, like APACHE or NGINX. These servers are already designed for high traffic, which is the ultimate goal, to have many students and instructors use this web interface. If we use RAPACHE, in the future there could be some scaling issues when there are many requests to the server.

Please let me know what you think?

**Comment by mikeizbicki** [comment]
That's a good question, but I don't want to use any of those other projects.  I specifically want everything done in bash so that any student that's taken cs100 could read through the entire codebase and understand everything.  As for scaling issues, bash should easily be able to handle all the students of a university the size of UCR using the project.
