### ISSUE TITLE
HW 4 Topic

### ISSUE THREAD

**Issue by lilajomok** [mikeizbicki/ucr-cs100#955]
I noticed there isn't a section about `stat`, `fstat`, and `lstat` in the syscalls tutorial, so I would like to write a tutorial about it and possibly `opendir`, `readdir`, and `closedir` if `stat` doesn't meet the words requirement. In other words, a tutorial about the syscalls used in HW1. It will follow the same format of the other syscall tutorials.

I'll be working on this by myself, but I'm open to teaming up with those interested in helping out (preferably those who were going to write a tutorial about `stat` or another syscall too). Let me know.

**Comment by mikeizbicki** [comment]
Sounds good!  I suspect that you'll have to write about all of those syscalls to get the right length for a 1 person assignment.

**Comment by levinlozenges** [comment]
I'd like to contribute! Even though the `stat` syscall and resulting `struct stat` acts as a storage bin for a file's external info, it's not straightforward to extract it and present it in a readable form for human eyes.

Perhaps we could also team up to write a tutorial on `open`, `close`, `read`, and `write` along with file descriptors to help future students confused with HW2, like we will be in the next few days? This could also tie in with also helping students with lab5 which also uses those syscalls. I think the reason why people had trouble with that lab was because the only documentation for those syscalls were found in the Linux man pages and `cp` indirectly used `open` and `close` to copy code with `read` and `write`.

**Comment by mikeizbicki** [comment]
My expectation from two people working together on this would be to also: 
1. Update the lab5 text to make it easier to follow.  This might mean specific links to the appropriate sections of the syscalls tutorial.
2. Tie this in with the bitwise operator tutorial.  You'll be needing lots of bitwise operators to handle all these functions.  That will mean your tutorial should link to the appropriate sections of their tutorial, and you should modify their tutorial to also link to yours.

**Comment by lilajomok** [comment]
So in summary:

> 1.  `stat`, `open`, `opendir` (and the others mentioned) syscall tutorials - tie it in with the bitwise ops tutorial and other syscalls 
> 2.  Update lab5 with links to syscalls tutorials and clarify it

for a 2-person project? Anything else I missed?

**Comment by mikeizbicki** [comment]
@goninety correct!

**Comment by levinlozenges** [comment]
Sounds good; we can meet up after class to talk about it. I'll be the guy called Jeff in a red beanie and a blue-red striped shirt. Looking forward to working with you Lila!

**Comment by lilajomok** [comment]
@jng017 Okay. Sounds good to me. See you later after class. I'll be towards the back of the classroom near the door at one of the left-handed desks.
